### ISSUE TITLE
Automatic build server

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#10]
_From [jared.c....@gmail.com](https://code.google.com/u/107361913114394030743/) on December 06, 2007 13:45:36_

It would be nice to have a server that builds this stuff every day with all
the lisps.  Careful of security issues.  (Chroot jail?)

_Original issue: http://code.google.com/p/acl2-books/issues/detail?id=9_

**Comment by acoglio** [comment]
Can this Issue be closed, or is there more to it than what we currently have on leeroy?

**Comment by ragerdl** [comment]
Haha, interesting find.  Yeah!  Definitely done!
