### ISSUE TITLE
`cw` not affected by ld standard-co redirection

### ISSUE THREAD

**Issue by mister-walter** [acl2/acl2#1008]
`ld`'s `:standard-co` redirection functionality does not affect `cw` calls.

To see what I mean, run this code in ACL2:
```
:q
(ld '((cw "hi there!"))
     :standard-co "/dev/null"
     :proofs-co "/dev/null")
```

On my machine I get the following output:
```
ACL2 !>:q

Exiting the ACL2 read-eval-print loop.  To re-enter, execute (LP).
* (ld '((cw "hi there!"))
     :standard-co "/dev/null"
     :proofs-co "/dev/null")
hi there!
NIL
:EOF
ACL2_INVISIBLE::|The Live State Itself|
```

I would have expected that "hi there!" be redirected to `/dev/null`, but it is output to the terminal instead. I'm not sure if this is a side-effect of `cw` not taking in `state` and thus not being affected by `ld`'s changes here. 

I have an ugly workaround for this which involves redefining the function `fmt-to-comment-window` in raw lisp to be a no-op, but ideally this would work! Being able to disable this output is especially useful in applications where ACL2 is queried programatically at a high frequency.

EDIT: Forgot to say I'm using SBCL 1.5.4 with ACL2 8.2 on Arch Linux.

**Comment by MattKaufmann** [comment]
Hi --

[I'm CCing acl2-books because I *think* that's where this reply should
go but I'm not sure it would otherwise.  Apologies if two copies of
the message are delivered.]

Your analysis seems spot-on to me.  The inability of cw to redirect
its output away from the standard output channel is basically due to
its not taking state, as you suggested:

> I'm not sure if this is a side-effect of `cw` not taking in `state`
> and thus not being affected by `ld`'s changes here.

This behavior is indeed documented -- quoting from :doc cw:

  .... Second, it neither takes nor
  returns the ACL2 [state]; logically cw simply returns nil, although
  it prints to a comment window that just happens to share the
  terminal screen with the standard character output [*standard-co*].

However....

I confess that at the moment, since cw is logically a no-op, I don't
know why there couldn't be a version of cw that further "cheats" by
looking at (standard-co state).  I'd be interested in others' opinions
on that, in particular J's (hence I'm CCing him on this reply).

But for now, your ugly workaround seems reasonable to me.  Perhaps a
better workaround would be to define your own variant of cw -- say,
cw-channel -- in a book with a trust tag, using include-raw.  In the
raw Lisp definition you could rebind *standard-co* to (standard-co
state).

Or perhaps better yet, perhaps you could avoid cw, which is kind of a
hack.  I realize that this might be inconvenient because of the need
to pass state around, but maybe it's worth biting the bullet and
trying to do that (as we generally do in the ACL2 source code).
Sometimes one can delay passing state around by returning "messages"
to be printed by a top-level function.  (If that's not clear, let me
know and I'll elaborate.)

-- Matt

**Comment by mister-walter** [comment]
Thanks for the quick reply!

Binding `*standard-co*` in raw Lisp seems much cleaner to me - I think I had originally assumed that ld was binding it and thus was confused by cw's documentation, but it makes sense now!

I should have specified that the `cw` calls I wish to quiet are in code not written by me. (in particular, they're in ACL2s) However, I can just ask Pete to add options to quiet those calls.

**Comment by jaredcdavis** [comment]
Hi,

FWIW, perhaps the following hideous code from
book/centaur/bridge/bridge-raw.lsp will be useful.

Cheers,
Jared

; Worker Output Setup.
;
; The goal here is to get printing to FMT, CW, etc., routed through the
; client's output stream.
;
; Binding *STANDARD-OUTPUT* is easy.
;
; Binding *STANDARD-CO* is slightly trickier.  The value of *STANDARD-CO* is
; just a symbol, e.g., ACL2-OUTPUT-CHANNEL::STANDARD-CHARACTER-OUTPUT-0, and
; functions like PRINC$ use GET-OUTPUT-STREAM-FROM-CHANNEL to look up the
; associated stream.  So, to fit into this scheme, we need to bind
; *STANDARD-CO* to a new symbol that is associated with our particular stream.
;
; Unfortunately, aside from *standard-co*, there are also several state globals
; that ACL2 uses to do printing.  These include standard-co (again), proofs-co
; and trace-co.
;
; The way these work is really complicated.  Basically if you do (global-symbol
; 'proofs-co), you'll get a symbol like ACL2_GLOBAL_ACL2::PROOFS-CO.  Even
; though this symbol doesn't have *s around its name, it's a special, and
; whatever value it's bound to is the name of the actual channel (not stream)
; to use.  After some poking around I found you can use PROGV to bind these.
; What a mess!

(defmacro with-acl2-channels-bound (channel &rest forms)
  `(progv
       (list (acl2::global-symbol 'acl2::proofs-co)
             (acl2::global-symbol 'acl2::standard-co)
             (acl2::global-symbol 'acl2::trace-co))
       (list ,channel ,channel ,channel)
     (progn . ,forms)))

(defmacro with-output-to (stream &rest forms)
  (let ((channel (gensym)))
    `(let* ((,channel        (gensym)))
       (setf (get ,channel acl2::*open-output-channel-type-key*) :character)
       (setf (get ,channel acl2::*open-output-channel-key*) ,stream)
       (unwind-protect
           (let ((*standard-output* ,stream)
                 (*trace-output*    ,stream)
                 (*debug-io*        ,stream)
                 (*error-output*    ,stream)
                 (*standard-co*     ,channel))
             (with-acl2-channels-bound ,channel . ,forms))
         ;; Invalidate the symbol's stream so the garbage collector can
         ;; reclaim the stream.
         (setf (get ,channel acl2::*open-output-channel-key*) nil)
         (setf (get ,channel acl2::*open-output-channel-type-key*) nil)))))

;; Basic test of this:
(assert (equal (let ((test (make-string-output-stream)))
                  (with-output-to test
                                  (format t "This is a format test~%")
                                  (cw "This is a cw test")
                                  (fmt "This is a proof output test"
                                       nil (acl2::proofs-co
acl2::*the-live-state*)
                                       acl2::*the-live-state* nil)
                                  (fmt "This is a standard-co test"
                                       nil (acl2::standard-co
acl2::*the-live-state*)
                                       acl2::*the-live-state* nil)
                                  (fmt "This is a trace-co test"
                                       nil (f-get-global
'acl2::trace-co acl2::*the-live-state*)
                                       acl2::*the-live-state* nil))
                  (get-output-stream-string test))
                "This is a format test
This is a cw test
This is a proof output test
This is a standard-co test
This is a trace-co test"))


On Tue, Jul 23, 2019 at 12:52 PM Andrew Walter <notifications@github.com> wrote:
>
> Thanks for the quick reply!
>
> Binding *standard-co* in raw Lisp seems much cleaner to me - I think I had originally assumed that ld was binding it and thus was confused by cw's documentation, but it makes sense now!
>
> I should have specified that the cw calls I wish to quiet are in code not written by me. (in particular, they're in ACL2s) However, I can just ask Pete to add options to quiet those calls.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
Jared C. Davis <jared.c.davis@gmail.com>
2911 Round Table Road
Austin, TX 78746
https://www.kookamara.com/jared/

**Comment by MattKaufmann** [comment]
Thanks, Jared!  I totally oversimplified -- I'm glad you have dealt
with this and shared your solution.
-- Matt

**Comment by mister-walter** [comment]
Dang, I should have thought to look at the bridge code - thank you for that code Jared!

**Comment by MattKaufmann** [comment]
I've gotten feedback from J Moore about this, and I think
we'll leave cw as is.  The problem with allowing cw to write
to a file is that files are part of the ACL2 state, so one
would be changing state without returning it.  That would
sort of make some theorems proved about state meaningless
(or to be more blunt: false).  Currently we imagine that cw
writes only to some "comment window" that isn't actually
part of state.

I'm closing this issue; it can always be reopened (I think)
if necessary.
