### ISSUE TITLE
Fix Milawa links

### ISSUE THREAD

**Issue by sbp** [acl2/acl2#1147]
Some Milawa links in the ACL2 documentation are broken. PR #1146 fixes this issue.

**Comment by sbp** [comment]
Fixed with the [merge of #1146](https://github.com/acl2/acl2/pull/1146#event-3482011018).

**Comment by MattKaufmann** [comment]
Thank you for fixing Milawa links!  I have updated the manual online:

http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index.html

In particular, the links look fine now:

http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index.html?topic=ACL2____MILAWA

I didn't notice until after I accepted the pull request that it was
made to master.  It's best to make them to the testing branch instead,
as per these instructions:

http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index.html?topic=ACL2____GITHUB-COMMIT-CODE-USING-PULL-REQUESTS

**Comment by sbp** [comment]
Thanks for applying this patch so quickly.

Sorry that I missed the branch instruction in the documentation. I'll definitely make sure that I submit any PRs from now on to the `testing` branch!
