### ISSUE TITLE
Arithmetic-2/meta/cancel-terms-meta.lisp seems to be broken in ACL2(r)

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#1148]
See http://leeroy.defthm.com/job/acl2-multiple-flavors-and-lisps-weekly/ACL2_PAR=no_p,ACL2_REAL=r,LISP=ccl/1088/console for details.

Not sure to whom to assign this.  Maybe @rubengamboa

**Comment by MattKaufmann** [comment]
I'll take a look. -- Matt

**Comment by MattKaufmann** [comment]
OK, I've fixed this; closing.
