### ISSUE TITLE
ACL2(s) defsort change broke ACL2(p) w/ waterfall parallelism build

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#1171]
As shown in http://leeroy2.defthm.com/job/acl2-multiple-flavors-and-lisps-monthly-regression-everything/ACL2_PAR=p,ACL2_REAL=no_r,LISP=ccl/19/console

```
 ACL2 !>
   | 
   | ACL2 Error in SET-WATERFALL-PARALLELISM:  Before changing the status
   | of waterfall-parallelism, either (1) override hints must be removed
   | from the default-hints-table or (2) waterfall-parallelism hacks must
   | be enabled.  (1) can be achieved by calling (SET-OVERRIDE-HINTS NIL).
   | (2) can be achieved by calling (SET-WATERFALL-PARALLELISM-HACKS-ENABLED T).
```

The way to know about this error before pushing to a testing branch is to build the books with ACL2(p) _and_ waterfall parallelism enabled.  It seems like enabling waterfall parallelism is somehow actually the default (likely instrumented in `books/GNUMakefile`) when building the books with ACL2(p) -- i.e., I didn't do anything special to enable waterfall parallelism when setting up Jenkins this most recent time.

At the moment, as a community, we don't expect folks to test books in ACL2(p) and ACL2(r) before committing them (which is reasonable imho).  I do wonder if we should enable those checks for automatic pushing from the `testing` branch, but I'm going to hold off on that for now.  Maybe it'd be nice if folks would informally commit to cleaning up such breakages if they're found after the fact, but there's certainly no agreed upon standard for any of it.

Regardless, I plan to fix it this time, so I've assigned the issue to myself.  cc: @pmanolios

**Comment by ragerdl** [comment]
Odd, it looks like @pmanolios already fixed the waterfall parallelism issue in https://github.com/acl2/acl2/commit/b9911af847a202618fe2318ab252bc68e8498c9c .  And those lines were add 12 days ago, so I don't know why the build is broken... looking into it.

**Comment by ragerdl** [comment]
Alright, gotten to the bottom of this.  It's a bit of an ironic problem.

(1) @pmanolios did a good job by realizing that the override hints present in the `sorting` book were going to cause problems for ACL2(p) with waterfall parallelism enabled.

(2) By default the Jenkins build does not build the ACL2(p) build with waterfall parallelism enabled.  This is in contrast to what I was thinking earlier.  I may want to enable waterfall parallelism by default in the ACL2(p) Jenkins build, but that's for another day.

(3) A call of `set-waterfall-parallelism` with a value that equals the current value should probably be a no-op.  Instead, even though the call could be a no-op in this case (it's already `nil`), ACL2(p) checks that there are no override hints in place, which causes the above error.  It would be better if ACL2(p) basically ignored calls that don't actually change the waterfall parallelism state.  Same goes for `set-parallel-execution`.  @MattKaufmann how do you feel about doing that?

(4) I can't wrap my head around whether it makes sense to disable `sorting` for ACL2(p).  Adding that cert-param is certainly the easiest thing to do, and I'll probably just do that for now.  OTOH, if ACL2(s) folks actually want to use parallelism and `sorting`, then we'll run into issues if we ever use an acl2-customization file that actually runs `sorting` with waterfall-parallelism enabled.

**Comment by MattKaufmann** [comment]
@ragerdl I have no objection to the idea proposed in (3).  It looks to me like there's no change to make to set-parallel-execution (see set-parallel-execution-fn).  For set-waterfall-parallelism, I think I'd move (check-for-no-override-hints ctx state) from set-waterfall-parallelism1 to set-waterfall-parallelism-fn, where I'd make the check just before (f-put-global 'waterfall-parallelism val state), but only when the new value is non-nil.  (And while we're at it, let's move the prog2$ stuff in set-waterfall-parallelism-fn down to f,there too.)  Let me know if you want me to make these changes, or you can send me code you'd like me to install.

**Comment by ragerdl** [comment]
@MattKaufmann Please go ahead at your convenience w.r.t. addressing (3).  Thanks!

**Comment by ragerdl** [comment]
W.r.t. (4), I added `;; cert_param: (non-acl2p)` to `sorting.lisp`, and I can't tell if it's helped or not. I'm telling cert.pl to build that file, which may mean `cert.pl` should actually try to build that file (not ignore me because of a cert_param).  Anyway, I'll probably stop digging, since (3) is going to fix the symptom.

**Comment by acoglio** [comment]
Closing this for now, as discussed with @ragerdl. It is not lost, it can always be reopened.
