### ISSUE TITLE
Need :set-gag-mode nil in Walking Tour

### ISSUE THREAD

**Issue by kazarmy** [acl2/acl2#1242]
This is just a short note stating that `:set-gag-mode nil` is needed for the Walking Tour of ACL2 8.3. Otherwise, the subgoals in https://www.cs.utexas.edu/users/moore/acl2/v8-3/combined-manual/index.html?topic=ACL2____Overview_02of_02the_02Simplification_02of_02the_02Induction_02Step_02to_02T do not appear in the prover output.

**Comment by MattKaufmann** [comment]
Thank you!  J and I will consider how best to fix this.  I'm pretty sure the reason for this issue is that The Walking Tour was developed before gag-mode was implemented.

**Comment by MattKaufmann** [comment]
Thanks again, @kazarmy.  I've updated the "bleeding-edge" online manual and the fix shows up here:

https://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index.html?topic=ACL2____The_02Proof_02of_02the_02Associativity_02of_02App

**Comment by kazarmy** [comment]
Looks good to me. Glad to be of help.
