### ISSUE TITLE
(tsubst 'x '(a . b) 'a) causes memory read error

### ISSUE THREAD

**Issue by kazarmy** [acl2/acl2#1253]
Program | Version
------ | -----
ACL2 | 8.3
CCL | 1.12 LinuxX8664

I mistakenly implemented `tsubst` as follows (as an answer to an exercise in https://www.cs.utexas.edu/users/moore/publications/acl2-programming-exercises1.html and admitted in `:program` mode):

```lisp
(defun tsubst (x y z)
  ;; Substitute x for each occurrence of y in the binary tree z.
  ;; (We can't call this ``subst'' because such a function is
  ;; already defined in ACL2.)

  (if (equal y z)
      x
    (cons (tsubst x y (car z)) (tsubst x y (cdr z)))))
```

When I ran the following in ACL2:

```lisp
(tsubst 'x '(a . b) 'a)
```

there was an abort with the following error:

```
***********************************************
************ ABORTING from raw Lisp ***********
********** (see :DOC raw-lisp-error) **********
Error:  Fault during read of memory address #xD0000000005
While executing: TSUBST
***********************************************
```

Tracing reveals that:

```
ACL2 p!>(trace$ tsubst)
 ((TSUBST))

ACL2 p!>(tsubst 'x '(a . b) 'a)
1> (ACL2_*1*_ACL2::TSUBST X (A . B) A)
  2> (TSUBST X (A . B) A)
    3> (TSUBST X (A . B) 1786706395136)

***********************************************
************ ABORTING from raw Lisp ***********
********** (see :DOC raw-lisp-error) **********
Error:  Fault during read of memory address #xD0000000005
While executing: TSUBST
***********************************************
```

so apparently the guard for `(cdr 'a)` wasn't triggered, nor did it return `nil`.

This is probably a problem with the underlying Lisp.

**Comment by solswords** [comment]
I think this is not a bug but just the intended behavior of program-mode functions.  See [guards-and-evaluation](https://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/?topic=ACL2____GUARDS-AND-EVALUATION), in particular "Guards and evaluation IV: functions having :program mode".

**Comment by MattKaufmann** [comment]
I absolutely agree with @SolSwords.  Lisp isn't required to do anything like guard-checking (and for efficiency, ACL2 is compiled with settings that tend to defeat type checks).  If one wants guard-checking on all :program-mode calls in ACL2, then one can get it as follows.

    ACL2 p!>:set-guard-checking :all

    Leaving guard checking on, but changing value to :ALL.

    ACL2 p!>(tsubst 'x '(a . b) 'a)


    ACL2 Error in TOP-LEVEL:  The guard for the function call (CAR X),
    which is (OR (CONSP X) (EQUAL X NIL)), is violated by the arguments
    in the call (CAR 'A).
    See :DOC set-guard-checking for information about suppressing this
    check with (set-guard-checking :none), as recommended for new users.
    To debug see :DOC print-gv, see :DOC trace, and see :DOC wet.

    ACL2 p!>

**Comment by kazarmy** [comment]
Oh ok, closing the issue.
