### ISSUE TITLE
"pattern" and "target" are swapped

### ISSUE THREAD

**Issue by kazarmy** [acl2/acl2#1255]
Seen in https://www.cs.utexas.edu/users/moore/acl2/v8-3/combined-manual/index.html?topic=ACL2____LOGIC-KNOWLEDGE-TAKEN-FOR-GRANTED-REWRITING (also seen in `current/manual`):

> It is important that you are familiar with the notions of a _pattern_ term being an instance of a _target_ term.

I think "pattern" and "target" should be swapped, and that it should read:

It is important that you are familiar with the notions of a _target_ term being an instance of a _pattern_ term.

**Comment by MattKaufmann** [comment]
Thanks!  Fixed in GitHub commit 7b32a29b42ddb974426eae15ab040b7f6cb0b5fc and in the "bleeding edge" manual (https://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index.html?topic=ACL2____LOGIC-KNOWLEDGE-TAKEN-FOR-GRANTED-REWRITING).  The Version 8.3 manual is static, so no change there.

**Comment by kazarmy** [comment]
There's another sentence a few paragraphs down that seems related:

> Suppose _pattern_ is an instance of some target term, _target_ that occurs in your goal conjecture.

There's that vague feeling that something is mixed up here, but I'm not quite sure what the correct sentence would be.

**Comment by MattKaufmann** [comment]
Right, I'm changing that sentence to the following: "Suppose some target term, _target_ that occurs in your goal conjecture is an instance of _pattern_."  Thanks for catching that.  I did a quick read of the rest of that topic and didn't notice any further problems, but if you see any, by all means please continue to point them out.  Thanks!  I've updated in GitHub commit c7e7bcc0916cd9aa32d14f37e1c6bd98f5c705ef (same commit message as last time, by accident) and I've updated the online manual as before.

**Comment by kazarmy** [comment]
Apart from _hypi_ not having a definition, which probably doesn't matter that much, there doesn't seem to be any other problems. Thanks for making the fixes!

**Comment by MattKaufmann** [comment]
I think that the "hypi" notation follows the usual ccnvention of referencing hyp1 and/or hyp2 etc. (which are defined in the "Theorem" display).  But please feel free to suggest wording that you think would be better.

**Comment by kazarmy** [comment]
I don't think the wording needs to be changed since it appears obvious what "hypi" should refer to, after a small moment disambiguating it from "hypk".

**Comment by bendyarm** [comment]
Why not use underbar as in subscript?  hyp_i and hyp_k.

**Comment by MattKaufmann** [comment]
Seems reasonable, but I'd rather not think about what else would have to change for consistency of style.  You and anyone else in the acl2-books group are welcome to edit the documentation.
