### ISSUE TITLE
Build failure using SBCL on Darwin ARM

### ISSUE THREAD

**Issue by sbp** [acl2/acl2#1294]
On `arm64` using `Darwin 20.4.0` and SBCL `2.1.2.nixos` I encounter the following build error caused by some code in `memoize-raw.lisp`:

```
  READ error during LOAD:

    Lock on package SB-VM violated when interning %READ-CYCLE-COUNTER while in
    package ACL2.

[...]

(SB-C:COMPILER-ERROR SB-C::INPUT-ERROR-IN-LOAD :CONDITION
 #<SB-EXT:PACKAGE-LOCKED-ERROR "interning ~A" {70079423E3}>
 :POSITION 9782 :LINE/COL (192 . 0) :STREAM #<SB-INT:FORM-TRACKING-STREAM
 for "file [...]/acl2-8.3/memoize-raw.lisp" {7007929443}>)
```

Judging from [the appropriate comment](https://github.com/acl2/acl2/blob/fbee64883114e1bcfd93c3f94c8c9e30e6e19e7b/memoize-raw.lisp#L198) in `memoize-raw.lisp` it seems that this code has given problems before. I decided to comment out [lines 192 to 219](https://github.com/acl2/acl2/blob/fbee64883114e1bcfd93c3f94c8c9e30e6e19e7b/memoize-raw.lisp#L192-L219) to see if that would fix it. The build process then completed, apparently successfully, but attempting to run the `saved_acl2` executable caused a segfault:

```
$ ./saved_acl2
[...]
read: Bad address
Segmentation fault: 11
```

I read some of the scant SBCL documentation about `PACKAGE-LOCKED-ERROR`, but at this point I'm not sure how to proceed. It is not currently possible to use `ccl`, `gcl`, or `clisp` on `darwin-arm64` because they fail to build with a variety of their own errors, in both Nix and Homebrew, so `sbcl` is the most reasonable option here.

**Comment by sbp** [comment]
The `%READ-CYCLE-COUNTER` bug seems to be fixed in `HEAD`, probably due to 292fa2c. But that commit takes effectively the same approach as my naïve fix, simply disabling that section of code when not running on x86. The `saved_acl2` executable from `HEAD`, which is currently fbee648, still produces a segfault.

**Comment by mayankmanj** [comment]
I am running ACL2-8.4 on my arm64 Darwin machine, and I did not come across the build issue. However, I noticed the segfault, and I filed a bugfix with SBCL recently -- details here: https://bugs.launchpad.net/sbcl/+bug/1939472.

That has fixed the segfault issue for me. Maybe it is the same issue for you. The fix has been pushed to SBCL master -- https://github.com/sbcl/sbcl/commit/8fa3f76fba2e8572e86ac6fc5754e6b2954fc774

**Comment by sbp** [comment]
Fantastic, thanks @mayankmanj! This fixed my issue.

To anybody who comes across this thread, I suggest installing `sbcl` from Homebrew using `--HEAD` for the easiest resolution:

```sh
brew install --HEAD sbcl
```

And then, as mentioned above, building ACL2 from `HEAD` too.

I'll close this issue, but perhaps it may be worth another ACL2 point release so that users on ARM can get 292fa2c from the versioned distribution. It also may be worth mentioning that Darwin ARM requires a post sbcl/sbcl@8fa3f76 sbcl in the ACL2 documentation, but perhaps this thread will be sufficient.

**Comment by kini** [comment]
292fa2c is included in ACL2 8.4 which just came out a few days ago. I'm working on updating the Nixpkgs expression :)

**Comment by kini** [comment]
@sbp Since you seem to be experimenting with ACL2 on Nix + ARM, could I ask you to review NixOS/nixpkgs#134081? I don't have an ARM machine to test on. The PR there incorporates a backport of sbcl/sbcl@8fa3f76 as well, so hopefully you should be able to build all the community books on ARM (:crossed_fingers:).

**Comment by sbp** [comment]
@kini Sure thing. Here's the output from the installation attempt:

https://gist.github.com/sbp/82eb125f6f80e3f49a8345ccb76b1fde

Looks like it failed compiling `openssl-1.0.2u` because its configure script doesn't support `darwin64-arm64-cc` as an OS/compiler target. Let me know if you want me to test it again, or change anything about the installation procedure.

**Comment by sbp** [comment]
@kini On your [edit question](https://github.com/acl2/acl2/issues/1294#issuecomment-898953607), I only installed `sbcl` from Nix and then used it to attempt to build from the ACL2 8.3 tarball manually, by [following the ACL2 manual](https://www.cs.utexas.edu/users/moore/acl2/v8-3/HTML/installation/installation.html). I didn't know about 8.4 until this thread, and even missed it initially when Mayank said about running it on ARM. The way I got 8.3 was:

```
curl -LO https://github.com/acl2-devel/acl2-devel/releases/download/8.3/acl2-8.3.tar.gz
```

And the SHA-256 of `acl2-8.3.tar.gz` is:

```
45eedddb36b2eff889f0dba2b96fc7a9b1cf23992fcfdf909bc179f116f2c5ea
```

**Comment by kini** [comment]
> Looks like it failed compiling `openssl-1.0.2u` because its configure script doesn't support `darwin64-arm64-cc` as an OS/compiler target.

Thanks for testing! Wow, that sounds more deeply broken than I expected... :( If openssl can't build, that must be affecting a lot of NixOS software on aarch64-darwin, right?

The `acl2` expression in nixpkgs attempts to build as many of the community books as possible, and as such it pulls in various dependencies. I'm not sure which one is indirectly pulling in openssl 1.0.2u (`acl2`'s own explicitly specified dependency on openssl should be resolving to 1.1.1k in nixpkgs master), but maybe your initial approach is the best one for now - that way you'll be able to more easily isolate which books and their dependencies are causing you trouble.

Installing the modified sbcl expression from the `let` at the top of the acl2 expression (which includes the sbcl/sbcl@8fa3f76 patch, disabled immobile space, and the appropriate `--dynamic-space-size` flag) instead of the default sbcl expression might still be useful to you, though.

**Comment by sbp** [comment]
The openssl situation isn't so bad because `openssl-1.1.1k` builds successfully, but you're right anyway in thinking that many Nix packages are broken on Darwin ARM. Generally I resort to installing packages from Homebrew when I get a Nix failure, leading to an awkward spread of packages between the two managers.

Thanks for the tip about the sbcl expression. I'll just wait until its default expression is fixed since Homebrew sbcl is working, but please do update this thread if you ever need any further help testing the nixpkgs acl2 expression.
