### ISSUE TITLE
Result substitution in `:returns` affects hints

### ISSUE THREAD

**Issue by acoglio** [acl2/acl2#1300]
The following example from @ericwhitmansmith exemplifies the problem:
```
(include-book "std/util/define" :dir :system)

;; This (artificial) example fails but should not.  Note the explicit
;; :expand hint.  However, for some reason, define changes the hint to
;; :EXPAND (FOO (FOO X)), which fails to match.  The function
;; STD::RETURNSPEC-SUBLIS seems to be the thing that changes the
;; hints.
(define foo (x)
  :returns (x acl2-numberp
              :hints (("Goal"
                     :expand (foo x)
                     ;; ensure that the :expand hint is needed:
                     :in-theory (disable foo (:t foo) (:e tau-system))
                     )))
  (fix x))
```

In a `:returns`, the result name (`x` in this case) represents a call of the function on the formals (`(foo x)` in this case). So, while it is appropriate to apply the substitution to the formula (`(acl2-numberp x)` to `(acl2-numberp (foo x))` in this case), it is arguably not appropriate to do that for the hints, which is what is happening above.

It could be argued instead that one should use `:expand x` in the hints, but it would seems a bit strange and non-explicit to me. Using result names that are disjoint from formal names should generally avoid these problems (unless one goes out of their way in writing strange hints), so another path to explore is to ensure that disjointness. But there is still an issue of what a result name in the hints should mean, i.e. whether itself or the function call.

My vote is that no substitution happens in the hints.

**Comment by solswords** [comment]
Fixed by [this commit](https://github.com/acl2/acl2/commit/830601082e1084b1bebcd9cbbb67b58899654571)
