### ISSUE TITLE
GCL 2.6.12

### ISSUE THREAD

**Issue by DennisYurichev** [acl2/acl2#1351]
Just so you know.
Latest ACL2 can't run with $SUBJ that coming with Ubuntu 20.04.3 LTS.

    GCL (GNU Common Lisp)  2.6.12 CLtL1    Fri Apr 22 15:51:11 UTC 2016

But this version is still mentioned here: https://www.cs.utexas.edu/users/moore/acl2/current/HTML/installation/requirements.html#Obtaining-GCL

**Comment by MattKaufmann** [comment]
Thank you for the feedback.  The installation instructions at https://www.cs.utexas.edu/users/moore/acl2/v8-4/HTML/installation/requirements.html#Obtaining-GCL say: "Note that ACL2 requires ANSI GCL version 2.6.12 or later."  But the banner you displayed shows "CLtL1", which means that your GCL is not ANSI.

**Comment by DennisYurichev** [comment]
Thanks. Had no idea about that.
