### ISSUE TITLE
DRAT proof checking

### ISSUE THREAD

**Issue by DennisYurichev** [acl2/acl2#1352]
How to do it?
I installed ACL2, ran "make basic", run "build" in acl2/books/projects/sat/proof-checker-itp13.
I tired the 'rat-1' file in acl2/books/projects/sat/proof-checker-itp13.
I run:
    ./run rat-1
Got this in run.out: http://sprunge.us/k65zhv
Probably, this is the essence: "Error:  The function PROOF-CHECKER-ITP13::VERIFY-FILE is undefined."

**Comment by MattKaufmann** [comment]
Hi,

I see a file, books/projects/sat/proof-checker-itp13/build, that
probably needs to be executed before you can execute ./run.

Regards,
Matt

**Comment by DennisYurichev** [comment]
I did...

**Comment by DennisYurichev** [comment]
In acl2/books/projects/sat/lrat I ran ACL2_DIR/books/build/cert.pl --acl2 ACL2 -j 8 */*.lisp
OK
In /home/i/Downloads/acl2/books/projects/sat/lrat/stobj-based I ran this:
./run.sh ../tests/uuf-100-1.cnf ../tests/uuf-100-1.lrat
Error:
"ERROR: file ./lrat-check does not exist."

**Comment by MattKaufmann** [comment]
Please see books/projects/sat/lrat/stobj-based/README, which discusses use of a save-exec command.

**Comment by DennisYurichev** [comment]
I did. Now another problem.

    ./run.sh "../tests/uuf-100-1.cnf" "../tests/uuf-100-1-partial.lrat"
     s FAILED
       (see ../tests/uuf-100-1-partial.out)

uuf-100-1-partial.out: http://sprunge.us/HDjVv7

**Comment by DennisYurichev** [comment]
But that succeeds, if typed from acl2 REPL (from README file)

  (include-book "lrat-parser")

  ; Examples:

  ; Succeeds (returns (value t)):
  (verify-lrat-proof "../tests/uuf-100-5.cnf" "../tests/uuf-100-5.lrat")

**Comment by MattKaufmann** [comment]
It looks like the book "run" wasn't included before the save-exec.  Please run 
the following commands from books/projects/sat/lrat/stobj-based/README and save a log file of that ACL2 session.

    (include-book "run")
    :q
    (save-exec "lrat-check" "Executable defining (lrat-check cnf-file lrat-file &optional incomplete-okp)")

Then do your ./run.sh command again, and then do the following; and save the entire shell log.

    cat uuf-100-1-partial.out

Finally, please send both logs.

**Comment by MattKaufmann** [comment]
Our most recent two messages crossed.  If you still want help with ./run.sh, please send the two requested logs.

**Comment by DennisYurichev** [comment]
Ah! Now it works. I probably used wrong LRAT file ('partial'), which is supposed to be FAILED.
Sorry for disturbing!

Now I wonder, does acl2 has scripts for DRAT proofs?

**Comment by MattKaufmann** [comment]
Regarding:

> Now I wonder, does acl2 has scripts for DRAT proofs?

Sorry, I haven't thought about this in awhile and I don't have
anything readily available.  However, I believe that the ACL2 lrat
checker is used in the yearly SAT competition.  You could ask
Marijn Heule (CMU Computer Science) if he has scripts.
