### ISSUE TITLE
LRAT proof check: probably a bug

### ISSUE THREAD

**Issue by DennisYurichev** [acl2/acl2#1355]
These CNFs are UNSAT.
*.proof file are generated by kissat.
*.lrat are generated by drat-trim.
But still, ACL2 reports "HARD ACL2 ERROR in VALID-PROOFP$-TOP:  Invalid formula!" for both.
https://yurichev.com/tmp/eden/

*eden2* is the same as *eden*, but duplicate clauses are removed.

**Comment by krobelus** [comment]
Minimal reproducer:

```
p cnf 1 1
1 -1 0
```

If I recall correctly, proof checkers assume that there are no tautological clauses, to simplify some algorithms.
I think this is a fine choice (tautological clauses are trivial to filter out, for example with `lingeling -s SAT_lib.eden.cnf -o - --clim=0`)
However, improving error messages would help a great deal.

Another issue: DIMACS comments (`c this is a comment`) are not supported in CNF files.

**Comment by MattKaufmann** [comment]
Thanks, @krobelus , for the info about an expectation of no tautological clauses and for \
the suggestion to improve the error message -- I've updated the solver accordingly
(commit 679e482f3af7ffa3e97a374b59ad67b4123f7b27), illustrated as follows.
After the following commands

    (include-book "<path_to_books/projects/sat/lrat/stobj-based/>run")
    (lrat-check "SAT_lib.eden.cnf" "SAT_lib.eden.lrat")

then we get the following output.

    HARD ACL2 ERROR in VALID-PROOFP$-TOP:  Invalid formula!
    The formula contains the alleged clause (1 -1), which contains conflicting
    literals 1 and -1.

I'm not currently planning to look into the comment issue.  I keep
busy actively maintaining the ACL2 system, but I haven't really thought
about the SAT solvers in several years.  I haven't heard of any problems
with usage at an annual SAT conference.

**Comment by DennisYurichev** [comment]
Maybe it's because their tools generate CNF instances without duplicate clauses and tautologies.
While mine can do that :)

**Comment by MattKaufmann** [comment]
As far as I know, my checkers can handle duplicate clauses.

**Comment by DennisYurichev** [comment]
Didn't mean to offend, sorry!
