### ISSUE TITLE
`$ make basic` fails to certify quicklisp/base.lisp: "base.cert seems to be missing"

### ISSUE THREAD

**Issue by zacque0** [acl2/acl2#1371]
Hi,

While building from source, I encountered this error : `**CERTIFICATION FAILED** for /home/.../acl2/books/quicklisp/base.lisp`

Here I attach the log file [base.cert.out](https://github.com/acl2/acl2/files/8320961/base.cert.out.txt). The main cause seems to be this: 
```
HARD ACL2 ERROR in INCLUDE-RAW:  Load of "base-raw.lsp" failed with
the following message:
Unable to load any of the alternatives:
   ("libssl.so.1.1" "libssl.so.1.0.2m" "libssl.so.1.0.2k" "libssl.so.1.0.2"
    "libssl.so.1.0.1l" "libssl.so.1.0.1j" "libssl.so.1.0.1f" "libssl.so.1.0.1e\
"
    "libssl.so.1.0.1" "libssl.so.1.0.0q" "libssl.so.1.0.0" "libssl.so.0.9.8ze"\

    "libssl.so.0.9.8" "libssl.so.10" "libssl.so.4" "libssl.so")
```
which states that `cffi` failed to locate `libssl.so`. Yet, I have no issue loading that directly from sbcl repl:
``` lisp
CL-USER> (require :cffi)
NIL
CL-USER> (cffi:define-foreign-library libssl
	   (:unix "libssl.so"))
LIBSSL
```

Then, at the end of the log file, there is this line: `base.cert seems to be missing`. And indeed I don't have `base.cert` in the directory `books/quicklisp`. So maybe that is the main issue?

My steps: 
1. Clone the git repo
2. Checkout tag 8.4
3. `make LISP=$(which sbcl)`
4. `make -j4 basic`.

Environment:
```
$ sbcl --version
SBCL 2.1.9

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

**Comment by ericwhitmansmith** [comment]
FWIW, there is some text about SSL here;
https://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/?topic=ACL2____QUICKLISP
but it seems to mostly be about Macs.

**Comment by zacque0** [comment]
> FWIW, there is some text about SSL here; https://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/?topic=ACL2____QUICKLISP but it seems to mostly be about Macs.

Thanks, it doesn't help, but it hints at the problem with my library search path. 

Since my system has non-conventional installation path using the `guix` package manager, I realise that this workaround solves the issue:
```sh
$ LD_LIBRARY_PATH=/path/to/lib make basic
```

However, that doesn't explain why I've no problem searching for `libssl.so` directly from the sbcl repl.


Note: LD_LIBRARY_PATH shell variable is not exported on my system because that doesn't work on Ubuntu. You have to configure at the system level in the directory `/etc/ld.so.conf.d/`. Since I'm using `guix` package manager, I didn't do that either.
