### ISSUE TITLE
XDOC ignores unknown tags

### ISSUE THREAD

**Issue by MattKaufmann** [acl2/acl2#1415]
Consider this form:

`(defxdoc foo
  :parents (top)
  :short "Test"
  :long "<p>Exponentiation: 3<sup>n</sup>.  Subscript: x<sub>i</sub>.</p>")`

We get the following at the terminal.

```
ACL2 !>:doc foo
ACL2::FOO -- Current Interactive Session
Parents: ACL2::TOP.

  Test

  Exponentiation: 3n.  Subscript: xi.


ACL2 !>
```

Sadly, that's how it looks in the web-based manual, too.  As far as I can tell, tags that are unknown to xdoc are simply ignored, including ones like `<sup>` and `<sub>` that are supported by html.

I think it would be good for an error to occur instead, perhaps with some sort of global setting that exempts certain tags from causing an error.  I wonder if anyone agrees (or better yet, would like to make such a change), or for that matter, disagrees.

**Comment by ericwhitmansmith** [comment]
Stricter checking seems good, but would it slow down building the manual?

**Comment by rubengamboa** [comment]
This may be close to blasphemy in the formal methods work, but I would probably prefer it to just pass through HTML tags without comment. That’s what markdown does, and it’s really convenient. If somebody writes “<foo>” in an xdoc, I say we take their word for it that <foo> is valid HTML (and I guess ignore it in other formats, such as emacs info).

Clear Skies,
Ruben

—
Ruben Gamboa
Professor
Dept. of Elec. Eng. and Comp. Sci.
University of Wyoming

On Aug 1, 2022, 1:48 PM -0600, Eric W. Smith ***@***.***>, wrote:
◆ This message was sent from a non-UWYO address. Please exercise caution when clicking links or opening attachments from external sources.


Stricter checking seems good, but would it slow down building the manual?

**Comment by MattKaufmann** [comment]
Thanks @ericwhitmansmith and @rubengamboa .  I'm OK with this either way.  I'll probably just close the issue in a few days if there aren't other responses, since yes, it might slow things down, and I see the point about allowing unknown tags.  This came up because I was using latex2html to generate html and then converting the html to xdoc, and discovered that I need to consider tags like `<sub>` that don't do anything (e.g., I'm manually converting `x<sub>i</sub>` to` x_i`).

**Comment by MattKaufmann** [comment]
Closing as suggested 7 days ago.
