### ISSUE TITLE
Make target "save-exec" sometimes fails to rebuild

### ISSUE THREAD

**Issue by gjurgensen** [acl2/acl2#1422]
The `save-exec` make target does not rebuild in some cases (the "then" branch on line 781):

https://github.com/acl2/acl2/blob/a6d27972ccb3d53782679e5ab2b90022c5c8cddf/GNUmakefile#L767-L791

The acl2-customization file may include books, introducing untracked, implicit dependencies. The make rule fails to rebuild when these implicit dependencies are updated.

Implicit dependencies introduced by the acl2-customization may be arbitrarily complex. Perhaps this conditional should be removed from the make target so that it always rebuilds.

**Comment by MattKaufmann** [comment]
Seems reasonable.  I've made a note to make that change this weekend, probably Saturday, if nobody objects before then.  I'll do it right now though if you want.

**Comment by gjurgensen** [comment]
Thanks Matt. Its not a pressing issue, so whenever you have time.

**Comment by MattKaufmann** [comment]
Fixed with git commit 6f3f564d54b16a0e87b502d1c9354a4a8540c61c.
