### ISSUE TITLE
Add website links to ACL2-help manual page

### ISSUE THREAD

**Issue by kazarmy** [acl2/acl2#1481]
I think it's better that there are links to https://utlists.utexas.edu/sympa/info/acl2-help and https://utlists.utexas.edu/sympa/info/acl2 in [the `ACL2-help` manual page](https://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index-seo.php/ACL2____ACL2-HELP) for more ways to access the archives. Google is surprisingly unhelpful regarding this access.

**Comment by MattKaufmann** [comment]
Great idea!  I've updated the manual accordingly with commit ea869c9cfe46f6fda0118574bd6a904b86db82b6.  (Feel free to edit it further by editing file `books/system/doc/acl2-doc.lisp`, in particular the form (`defxdoc acl2-help ...)`.)
