### ISSUE TITLE
In :DOC at the terminal and acl2-doc, delimiting italicized and bold text with underscores

### ISSUE THREAD

**Issue by MattKaufmann** [acl2/acl2#1487]
I'd appreciate comments on this Issue in the next couple of days from anyone who types :DOC at the terminal or uses the acl2-doc browser.

I'm considering making a small change to how documentation is displayed at the terminal (and thus in the acl2-doc browser): wrapping italicized text in underscores (_).  I'd probably also do the same thing for bold text.

Here for example is a snippet from the source for :DOC make-event, followed by how it would print under this proposal.

------------------------------

:DOC make-event

```
 <p>We assume basic familiarity with the ACL2 <i>state</i>.
```

... would print as:

```
  We assume basic familiarity with the ACL2 _state_.
```

------------------------------

I realize there might be better improvements to make where italics are indicated, e.g.:

(a) modify the :DOC topic to use quotes, links, caps, or other indicators;

(b) change the printer to put out special characters that can be interpreted to demarcate italicized text; or

(c) surround the text with * instead of _ .

I'm definitely not offering to consider those!  I'm only looking to make a small, easy change that could improve readabiliity, so (a) is out, and so is (b) since I suspect that won't work in all environments (leading to more work).  I don't like (c) because * already occurs plenty; I think _ is more likely to stand out as a delimiter.

The example above shows single normal English word (namely "state") in descriptive text.  Here are some examples of other cases in case you're interested.

------------------------------

:DOC linear

```
 <p>The technical notion referenced above depends on the notion of
 <i>fn-count</i>, the number of function symbols in a term, and
 <i>pseudo-fn-count</i>, which is ....
```

... would print as:

```
  The technical notion referenced above depends on the notion of
  _fn-count_, the number of function symbols in a term, and
  _pseudo-fn-count_, which is ....
```

------------------------------

:DOC introduction-to-key-checkpoints

```
 <p>When a proof attempt fails, ACL2 prints some <i>key checkpoints</i>.  These
 are formulas that we think you should look at.  There are two kinds printed:
 key checkpoints <i>before an induction</i>, and key checkpoints <i>under a
 top-level induction</i>.
```

... would print as:

```
  When a proof attempt fails, ACL2 prints some _key checkpoints_.  These
  are formulas that we think you should look at.  There are two kinds
  printed: key checkpoints _before an induction_, and key checkpoints
  _under a top-level induction_.
```

------------------------------

:DOC interesting-applications

```
 <p>ACL2 was used at <b>IBM</b> to verify the floating point divide and square
 root on the <b>IBM Power 4</b>.  (See Jun Sawada. ``Formal verification of
 divide and square root algorithms using series calculation''. In
 <i>Proceedings of the ACL2 Workshop 2002</i>, Grenoble, April 2002.)</p>
```

... would print as:

```
  ACL2 was used at IBM to verify the floating point divide and square
  root on the IBM Power 4.  (See Jun Sawada. ``Formal verification of
  divide and square root algorithms using series calculation''. In
  _Proceedings of the ACL2 Workshop 2002_, Grenoble, April 2002.)
```

------------------------------

:DOC introduction-to-hints

```
 <p>The most common hint is to enable and/or disable a particular rule on some
 particular subgoal.</p>

 <code>
 (defthm <i>name</i>
         <i>formula</i>
         :hints ((\"Subgoal *1/3.2''\" :in-theory (disable nth-nthcdr))))
 </code>
```

... would print as:

```
  The most common hint is to enable and/or disable a particular rule on
  some particular subgoal.

    (defthm _name_
            _formula_
            :hints (("Subgoal *1/3.2''" :in-theory (disable nth-nthcdr))))
```

------------------------------
[end]

**Comment by gjurgensen** [comment]
One thought is that you might use [ANSI escape codes](https://en.wikipedia.org/wiki/ANSI_escape_code#SGR_(Select_Graphic_Rendition)_parameters) to actually print as bold and/or italicized. The code to bold text is `\033[1m`, the code to italicize is `\033[3m`, and to reset it is `\033[0m`. For instance, The following string:
```bash
ACL2 was used at \033[1mIBM\033[0m to verify the floating point divide and square root on the \033[1mIBM Power 4\033[0m. See Jun Sawada. ``Formal verification of divide and square root algorithms using series calculation''. In \033[3mProceedings of the ACL2 Workshop 2002\033[0m, Grenoble, April 2002.)
```
Should render as:
> ACL2 was used at **IBM** to verify the floating point divide and square root on the **IBM Power 4**.  (See Jun Sawada. Formal verification of divide and square root algorithms using series calculation''. In _Proceedings of the ACL2 Workshop 2002_, Grenoble, April 2002.)

Some terminals might not render these as intended though. For instance, my emacs shell will print the italicized text as underlined instead, but that seems fine to me.

This might fall under your option (b) and/or be more complicated than what you were hoping to take on. In that case, I like the underscore option you put forward and agree it is a big improvement in readability.

**Comment by MattKaufmann** [comment]
Thanks for the feedback!  Yes, that's the sort of thing that I had in mind with (b).  But now I'm thinking I might make the delimiters be user-modifiable (via an ACL2 table, or zero-ary attachable functions, or maybe state globals), so that a user can get true italic and bold where their environment supports that -- so thanks for the codes and the link.

**Comment by MattKaufmann** [comment]
I did an experiment using echo and ANSI escape codes that printed nicely under native Emacs, but not in an Emacs running under screen.  That sort of thing is why I think I'll use underscore by default and let other behavior be up to the user.

**Comment by MattKaufmann** [comment]
This was completed with commit d19635b1ca7a07971e60636b0c930cdb04b97e5c.  I decided to follow the suggestion from @gjurgensen (thanks!) and display text with fonts by default, as explained in the release note that I quoted in the commit message.  Note that to see the change in acl2-doc in an already-running Emacs, then in addition to what I said in the commit message about loading acl2-doc.el, you'll also need an updated documentation file, which I've already put in the web (you can use the D option in acl2-doc to download it).

I'll improve :DOC xdoc::terminal soon to clarify that one might get underlining instead of italics.

I'll close this now but if there are problems, it can be reopened.

**Comment by MattKaufmann** [comment]
It looks like although searching in acl2-doc more or less works, it doesn't quite work right.  I plan to look into this soon.

**Comment by MattKaufmann** [comment]
I fixed bug in acl2-doc searching with commit c5c3dff6be840bdfa86248b5d05f73be6b0de52d.  So I'm closing this again. To get the effect of this fix you can issue the D command in acl2-doc, since I have just now updated the manual on the web.

Note that in spite of my comment above about xdoc::terminal, I didn't change it; it already mentioned that one might get underlining instead of italics.

**Comment by MattKaufmann** [comment]
Sigh, sorry about the noise; reopening because acl2-doc search is still not fully working.  The problem is that SGR characters are contributing to the calculation of where to insert a newline in the acl2-doc buffer, but there are no SGR characters in the acl2-doc-search buffer.  I'm working on how to fix this problem.

**Comment by MattKaufmann** [comment]
Fixed, as far as I can tell (finally).  To see the fixes in acl2-doc, reload Emacs file acl2-doc.el and either rebuild the documentation or use `D` inside acl2-doc.
