### ISSUE TITLE
Tshell bad pid line error

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#174]
_From [rage...@gmail.com](https://code.google.com/u/102895947197065323718/) on April 14, 2014 17:02:58_

When one: (1) runs stv-debug, which launches gtkwave, (2) leave gtkwave open and (3) launch glucose via GL, one can see the following error:

; SATLINK: writing /tmp/dlrager-31544-satlink: 0.94 sec, 238,484,960
bytes

***********************************************
Note:  TSHELL error: bad pid line: .
  Will attempt to exit the proof in progress;
  otherwise, the next interrupt will abort the proof.
***********************************************

It'd be good to fix this at some point.  Maybe I'll do so, but a work around for now is:

:q
(tshell-stop)
(lp)
(tshell-ensure)

_Original issue: http://code.google.com/p/acl2-books/issues/detail?id=173_

**Comment by jaredcdavis** [comment]
This should definitely be fixed by shellpool.
