### ISSUE TITLE
support building documentation for ACL2 and most books in all supported Lisps

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#189]
_From [matthew.j.kaufmann@gmail.com](https://code.google.com/u/matthew.j.kaufmann@gmail.com/) on June 19, 2014 10:32:20_

Making the documentation is currently broken for LispWorks, as well as
(I think) for Allegro CL and probably some others of the Lisp
implementations on which ACL2 can be built.  The issue is oslib (at
least for LispWorks, where certification with USE_QUICKLISP=1 failed
for oslib/tests/mkdir.lisp).  Jared Davis points out that while he's
worked hard on this sort of thing, and while it would be great for
oslib functions to work in all of those Lisps, he's probably not
willing to fix this problem.  Any volunteers?

Note that before switching to XDOC, ACL2 documentation could (as far
as I know) be built on any Lisp for which ACL2 itself could be built.
It would be nice to regain that state of affairs.  This isn't a
pressing issue, since we distribute the documentation with ACL2
releases and I frequently put up "bleeding edge" updates at: http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index.html But it has been useful over the years to run ACL2 for each of its
supported Lisps on as many books as possible, as a way of finding
bugs, and also to avoid reliance on particular Lisp implementations,
which over the decades have come and gone.

_Original issue: http://code.google.com/p/acl2-books/issues/detail?id=188_

**Comment by jaredcdavis** [comment]
I think this is resolved enough that I am going to close it.  The manual builds under at least CCL and SBCL.  If there are particular oslib books or other books that do not certify on certain Lisps, then we can open issues about those specific books...
