### ISSUE TITLE
Cleanup orphan VL :doc topics

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#249]
There are currently a bunch of vl-related :doc topics at the top-level.  This isn't really a surprise as there has been a lot of fantastic work on VL recently, but we should clean these up before 7.0.

**Comment by MattKaufmann** [comment]
I wonder if xdoc could automatically create a top-level
topic, ORPHANS (say), to hold any topics without a parent.
I agree with the preceding comment, about it being "fine for
the manual to have bugs like this", but if it's easy to
automate hiding those orphans somehow, that would be nice.
I think people increasingly go to the bleeding-edge manual
and might find the extra top-level topics to be distracting.
