### ISSUE TITLE
Lessen the amount of memory required to build the manual

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#275]
Fork dies during zip.sh stage of saving the manual.  This is kind of weird, and I kind of expect it to go away as a real problem on its own (it came up out of nowhere).  But, the continuous integration server that I'd like to make public for the community is running out of memory.  The solution might be to rework rmtree, tshell, or zip to not require a fork.  Also, I plan to see if I can pull out 4 more GB from my host OS and see if I can allocate some more swap space, since the extra memory supposedly isn't a real requirement.

Background conversation:

(11:31:12 AM) DR2: man, xdoc::save keeps failing in the zip stage for me, because it can't allocate memory to fork the process
(11:31:24 AM) DR2: what's particularly strange is that this is just all of a sudden an issue
(11:31:31 AM) DR2: and I see that I have at least 10gb of ram free
(11:31:34 AM) DR2: any ideas?
(11:31:43 AM) DR2: this is for my home CI server btw
(11:32:14 AM) DR2: (well, 10gb after the process finishes, but I don't think saving the xdoc manual takes 10GB?)
11:43:26 AM) clop: DR2, this is a fundamental problem with fork
(11:43:41 AM) clop: it can just segfault if the process is too big
(11:43:42 AM) DR2: because it does a direct-copy of all memory?
(11:43:55 AM) DR2: as opposed to just referencing the previous memory?
(11:44:02 AM) clop: it uses "copy-on-write" pages 
(11:44:17 AM) DR2: there's not much writing going on, aye?
(11:44:18 AM) clop: which, in theory, are basically free until you actually write to them
(11:44:20 AM) clop: but
(11:44:33 AM) clop: to create those pages the OS needs to believe it can fulfill the memory requeset
(11:44:51 AM) DR2: oh, bah
(11:44:54 AM) clop: there is a horrible thing called overcommit that tries to speculate that there'll be enough memory
(11:45:02 AM) clop: but if you enable it and you're wrong...
(11:45:11 AM) clop: you can get totally hosed
(11:45:21 AM) DR2: like your filesystem gets hosed?
(11:45:26 AM) clop: no
(11:45:42 AM) clop: like, some other horrible crash
(11:45:44 AM) clop: of the program
(11:46:00 AM) DR2: if I have swap enabled, shouldn't that count towards my memory ceiling?
(11:46:01 AM) clop: i think Linux can just start killing random processes too
(11:46:06 AM) clop: yes
(11:46:20 AM) clop: but the best way to avoid this is not to fork
(11:46:30 AM) clop: or fork early (a la tshell)
(11:47:11 AM) clop: probably we need to rework oslib::rmtree to not use sys-call
(11:47:18 AM) clop: there's a bozo there
(11:47:27 AM) DR2: well, I can make an issue on it
(11:47:28 AM) clop: but lisp file system stuff is... a total wasteland
(11:47:50 AM) clop: you could also try turning down the set-max-mem call
(11:47:56 AM) clop: in the documentation, to see if it might possibly help
(11:48:24 AM) DR2: oh,that's funny
(11:48:32 AM) DR2: it requests exactly the amount of memory that I have free
(11:48:45 AM) clop: it will likely take longer with less memory
(11:48:47 AM) clop: but it might work

**Comment by ragerdl** [comment]
This has surfaced again on my build server (and on a machine at work too).  I think we probably won't do anything about it, as rebuilding will probably work.  But, I wanted to add another data point.

**Comment by ragerdl** [comment]
http://leeroy.defthm.com/job/acl2-testing/126/console

**Comment by jaredcdavis** [comment]
This is hard.  On one hand it would be nice to be able to build the manual on modest machines.  On the other, more memory helps the manual build faster, etc.  It's hard to know the right balance to strike.  I'm not sure how important it is to be able to build the manual on a small build server...

**Comment by ragerdl** [comment]
It's got 12 gig of ram in the VM, which strikes me as pretty decent.  I may need to give up on the idea of not having swap space.

**Comment by ragerdl** [comment]
Turns out I have 4 GB of swap space too, so that's 16 GB.

**Comment by ragerdl** [comment]
@jaredcdavis When I re-read the conversation, your advice was "probably we need to rework oslib::rmtree to not use sys-call."  If I were to investigate this, would that be what I'd need to do?

**Comment by jaredcdavis** [comment]
You might try enabling overcommit if you're dying on fork.  On the other hand, overcommit has a lot of problems and you may not want to enable it.  Aside from that, avoiding fork when there are many GB allocated may be the way to go...
 - Reworking `oslib::rmtree` to avoid `sys-call` would probably be a sensible first step.  The [osicat manual](https://common-lisp.net/project/osicat/manual/osicat.html) suggests there's a `delete-directory-and-files` function which may be a pretty easy replacement.
 - You may also need to rework `xdoc::save` to use something other than `sys-call` to invoke the zipping script.  It would probably be just fine to rework this to be based on `tshell`, which could avoid the problem.

**Comment by ragerdl** [comment]
It looks like `osicat:delete-directory-and-files` doesn't work on files.  Here's the error message I get when building the oslib copy tests (which start by removing a file):

```
OSLIB !>>Test: primitive copy file to non-existent file.

***********************************************
************ ABORTING from raw Lisp ***********
Error:  #<ENOTDIR "[No syscall name]" 20 :ENOTDIR "Not a directory">
***********************************************
```

As a work-around, I plan to first test to see if it's a file, and then remove the file using `cl:delete-file`.  And if it's a directory, then I'll call `osicat:delete-directory-and-files`

**Comment by ragerdl** [comment]
Okay, that seems to work.  Thanks for writing all of those copy.lisp tests!

**Comment by ragerdl** [comment]
The rmtree changes which I've made (and are still just in the `testing` branch) seem to work.  The build is now getting hung up on zip.sh.

http://leeroy.defthm.com/job/acl2-testing/138/console

**Comment by ragerdl** [comment]
It seems like my zip.sh fix (found in https://github.com/acl2/acl2/commit/097a9404ae0982459e975d45d922004b7c3907d5 ) works.  Closing!
