### ISSUE TITLE
Cleaning fails to remove large executables books/centaur/getopt/demo2.*

### ISSUE THREAD

**Issue by MattKaufmann** [acl2/acl2#305]
In the books directory, neither "make clean"  nor "make moreclean" gets rid of some large executables:

    % ls -l books/centaur/getopt/demo2.*
    -rw-rw-r-- 1 kaufmann acl2 313360432 Nov  3 17:51 books/centaur/getopt/demo2.core
    -rwxrwxr-x 1 kaufmann acl2 261507240 Oct 25 09:57 books/centaur/getopt/demo2.gcl
    -rw-rw-r-- 1 kaufmann acl2      4505 Sep 19 14:21 books/centaur/getopt/demo2.lisp
    -rwxrwxr-x 1 kaufmann acl2 146874368 Nov 10 09:02 books/centaur/getopt/demo2.lw
    -rw-r--r-- 1 kaufmann acl2 176374000 Nov  9 15:07 books/centaur/getopt/demo2.lx86cl64
    %

**Comment by jaredcdavis** [comment]
It looks like `worklispext` files are created by ACL2 when it saves images on many Lisps.  See `acl2-init.lisp`.  It seems safe to have clean.pl remove these, so I'll add it to the list of files to clean up.
