### ISSUE TITLE
Cleanup script that builds manual a little bit

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#334]
In distribute-manual.sh:
-- `perl xdata2sql.pl` is running twice.  We can probably get rid of the second call.

-- Also, pick one way of executing perl scripts, so I'd change `./xdata2sql4seo.pl`
to `perl xdata2sql4seo.pl`

**Comment by acoglio** [comment]
Closing this, as discussed with @ragerdl,  as it may no longer be relevant.
