### ISSUE TITLE
Add parallel-universe-twin feature to xdoc

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#337]
I think a notion of "see also" that would show up on the top right of each xdoc manual page would be useful.  Right now I find myself doing a combination of "parents", "subtopics" and manually writing `see also @(see foo)` to make such links.

For example, `alist-keys` would show up right-aligned next to `ACL2-built-ins` in topic `strip-cars`

This would be a way of expressing the notion that a pair of topics are somehow distant twins -- that they serve similar purposes, except they work with different frameworks.

I'm sure someone can come up with a better name.

**Comment by jaredcdavis** [comment]
I'm inclined to mark this as wontfix.

The legacy documentation system had [cite symbols](http://www.cs.utexas.edu/users/moore/acl2/v6-3/DOC-STRING.html) (see `:cite`) that could be used to do something like what you're suggesting.  This is fine, I guess, but it sort of seems like adding more work and things to maintain for documentation writers.

Perhaps as a counter proposal, I've thought about generating, for instance, for each topic `foo`, a list of "linked to by" topics, perhaps weighted by some heuristic that considers, e.g., how many times they link to `foo`, and also their importance score.  This list could be put on the right of the content, and would at least show *some* relationship between `alist-keys` and `strip-cars` without having to have `:parents` or similar.

Of course that would be some work, and I have no idea when I'll get around to it.

**Comment by ragerdl** [comment]
Makes sense, I'll close as wontfix.
