### ISSUE TITLE
deffixtype output bug

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#350]
When the following script runs, it kind of appears that the deffixtype has succeeded (certainly, to someone unfamiliar with the implementation of deffixtype it appears as such).  Yet it fails, without reporting any error (the easiest way to see that it has failed is to look in the history).

```
(defmacro u32-p (x) `(unsigned-byte-p 32 ,x))

(include-book "centaur/bitops/top" :dir :system)

(defun u32-fix (x) (if (u32-p x) x (loghead 32 (nfix x))))

(fty::deffixtype u32 :pred u32-p :fix u32-fix :equiv u32-equiv :define t)

(pbt 0) ; missing deffixtype event
```

This appears to be from the version of fixtype.lisp that's from Feb 18th.

To anyone seeking a temporary work-around: one can do a :trans1 of the deffixtype call and submit the enclosed encapsulate.  This shows that the thing that causes the unspoken error is that I didn't verify the guards of u32-fix.

**Comment by solswords** [comment]
Yeah, I noticed that.  Another workaround is to supply :verbosep t.
Probably it is just inhibiting error output and shouldn't do that.
