### ISSUE TITLE
assert! can't modify state

### ISSUE THREAD

**Issue by jaredcdavis** [acl2/acl2#356]
I really like `assert!` and use it all over.  Unfortunately it doesn't work when your tests involve `state`.

It would be nice if you could write something sort of like:

```
(assert! (b* (((mv val state) (random$ 10 state)))
           (< val 10))
```

I see that there's an `assert!-stobj` macro, but it doesn't seem to work on `state`.  Perhaps there's something more general we could write, to try to provide a very simple interface that "just works" whether there are stobjs or not.

**Comment by MattKaufmann** [comment]
Jared, below is a macro that does approximately what you
want.  You're welcome to add it, or some variant of it, to
books/misc/assert.lisp.  Notice in the "success" example
below the use of mv, since the term you wrote isn't actually
well-formed.  Of course, you might prefer a different
interface, but I'm not sure what you'd prefer.  Also, I like
your idea of combining these various assert macros into a
single macro, but I'll leave that to you or whoever wants to
think about what interface they'd find convenient.

```

(defun assert!-state-body (assertion form)

; Assertion should evaluate to (mv val st), where val is an ordinary value and
; st is a stobj.  See also assert!-body.

  `(mv-let (result state)
           ,assertion
           (if result
               (mv nil ',(or form '(value-triple :success)) state)
             (er soft 'assert!
                 "Assertion failed:~%~x0"
                 ',assertion))))

(defmacro assert!-state (&whole whole-form
                                assertion &optional form)

; Assertion should evaluate to (mv val st), where val is an ordinary value and
; st is a stobj.  See also assert!.

  (list 'make-event (assert!-state-body assertion form)
        :on-behalf-of whole-form))

(include-book "std/util/bstar" :dir :system)

; success
(assert!-state (b* (((mv val state) (random$ 10 state)))
                   (mv (< val 10) state)))

; failure
(assert!-state (b* (((mv val state) (random$ 10 state)))
                   (mv (> val 10) state)))

```

**Comment by MattKaufmann** [comment]
Assert-event does this just fine now.  Below is an example.  So, I'll closing this Issue.
    ACL2 !>(include-book "std/util/bstar" :dir :system)

    Summary
    Form:  ( INCLUDE-BOOK "std/util/bstar" ...)
    Rules: NIL
    Time:  0.12 seconds (prove: 0.00, print: 0.00, other: 0.12)
     "/Users/kaufmann/acl2/acl2/books/std/util/bstar.lisp"
    ACL2 !>(assert-event (b* (((mv val state) (random$ 10 state)))
                           (mv (< val 10) state))
                         :stobjs-out '(nil state))
     :PASSED
    ACL2 !>(assert-event (b* (((mv val state) (random$ 10 state)))
                           (mv (= val 100) state))
                         :stobjs-out '(nil state))


    ACL2 Error in ASSERT-EVENT:  Assertion failed on form:
    (B* (((MV VAL STATE) (RANDOM$ 10 STATE))) (MV (= VAL 100) STATE))


    ACL2 !>
