### ISSUE TITLE
In books/ make TAGS fails on Mac

### ISSUE THREAD

**Issue by MattKaufmann** [acl2/acl2#370]
Bob Boyer reported the following problem, making TAGS in books/, and I
was able to repeat it on my Mac as shown:

```
~/acl2/acl2/books$ make TAGS ACL2=acl2
ACL2_SYSTEM_BOOKS is /Users/kaufmann/acl2/acl2/books
...
xargs: illegal option -- -
usage: xargs [-0opt] [-E eofstr] [-I replstr [-R replacements]] [-J replstr]
     [-L number] [-n number [-x]] [-P maxprocs] [-s size]
     [utility [argument ...]]
make: *** [TAGS] Error 1
~/acl2/acl2/books$ 
```

**Comment by jaredcdavis** [comment]
Hi,

Here is what we use internally at Centaur to avoid this problem in a context where we have too many books for bash to handle even on Linux.

```
# Horrible hacks to avoid stupid "argument list too long" errors
#
# Credit for this hack:
#   http://blog.melski.net/2012/01/03/makefile-hacks-automatically-split-long-command-lines/

define max_args # DO NOT TOUCH THIS
  $(eval _args:=)
  $(foreach obj,$3,$(eval _args+=$(obj))$(if $(word $2,$(_args)),$1$(_args)$(EOL)$(eval _args:=)))
  $(if $(_args),$1$(_args))
endef

define EOL # DO NOT TOUCH THIS, BOTH LINES ARE NECESSARY


endef

# DO NOT TOUCH THIS.  We split the list of TAG_DEPS into 100-arg chunks.
TAGS: $(TAG_DEPS)
    @echo "Making TAGS"
    @rm -f TAGS
    @$(call max_args, etags -a, 100, $(TAG_DEPS))
```

I have no idea how portable this is, but it seems to work well for us...

Cheers,
Jared

**Comment by MattKaufmann** [comment]
Bob Boyer sent the following email, which I post here with his permission.
Not sure who will actually change books/GNUmakefile -- perhaps whoever
is tired of waiting for a fix.

Here is an alternative to making the TAGS file for books, to work around
some
error involving - and -- that I previously reported.

My method has, I think, the advantage that it will not break by passing
etags
so many thousands of names via xargs.   At least on some operating systems.
There are still limits I fear to the number of arguments you can pass to a
shell command.  Here is my suggestion:

  cd ~/acl2/books ; rm -f TAGS ; touch TAGS ; find . -name "*.lisp" -exec
etags --append {} \;

The TAGS file this generates has 155,000 entries.  75,000 theorems.  I mean
DEFTHMs.  Only 38,000 DEFUNs.  That's about two theorems per concept!
Which is more amazing, the number concepts or the number of theorems?

But I do urge you to scrutinize the resulting TAGS file to see if it works
for
you before passing it on.  I don't get anything right any more.

Bob

**Comment by ragerdl** [comment]
This doesn't actually help, because it also uses xargs, but the conversation would be incomplete without a pointer to it. It's a command that builds the tags but skips workshop directories and directories with a few other choice names.

https://github.com/acl2/acl2/blob/master/books/build/etags.sh

**Comment by MattKaufmann** [comment]
On my Mac I tried etags.sh, or more accurately the command in the comment near the end of that file (but with a relative  pathname).  It worked!  (See log below; also, I used the TAGS file successfully a couple of times.)  So I wonder if the TAGS argument in books/Makefile should just call this script.

    ~/acl2/acl2/books$ find . \( -path ./workshops -o -path ./del -o -path ./legacy -o -path ./output -o -path ./another/del  \) -prune -o -name '*.l*sp' | xargs build/etags.sh --append
    etags: skipping ./workshops: it is not a regular file.
    ~/acl2/acl2/books$

**Comment by MattKaufmann** [comment]
It's fine with me to close this.  The problem does not show up on my current Mac.  Actually there's a target TAGS-acl2-doc in the main GNUmakefile (as opposed to books/GNUmakefile) that might do the same thing (for what that observation is worth).  I doubt that anyone wants to mess with any of this.
