### ISSUE TITLE
books/centaur/quicklisp/clean.sh dependence on git foils release

### ISSUE THREAD

**Issue by MattKaufmann** [acl2/acl2#379]
There are git commands in books/centaur/quicklisp/clean.sh,
but the ACL2 release process involves a snapshot that avoids
the .git directory.  Jared suggested that I create this Issue, for
him to address at his leisure (if at all) -- I can easily work around
this at release time, simply by temporarily commenting out the
git-related parts of that file (which Jared suggests is probably
good enough).

**Comment by ragerdl** [comment]
@MattKaufmann looks like you did this in commit a5d7b83e519a0b7d621d74b9cb89da7b2f58fc6d .  Shall we go ahead and close this issue?

**Comment by MattKaufmann** [comment]
Right -- thanks, David.  I'm closing this issue.
