### ISSUE TITLE
Change default title of ACL2____TOP to something that indicates it's the combined manual

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#385]
Not a big deal but "XDOC - [topic name]" should probably be changed to something more like "ACL2 Manual -- top"

**Comment by ragerdl** [comment]
For my own reference, would a similar approach for the width of the left hand side column work?  Or is that an entirely different system since that's probably decided by the style sheet.

**Comment by jaredcdavis** [comment]
To change the navigation size you might edit `$navsize` in `style.scss` and then regenerate the actual `.css` stylesheets using the `Makefile`.  I don't know whether it will work smoothly---there may be other hard-coded values in the style sheet that only work well with the current $navsize.  I don't know of an easy/principled way to change this via Javascript.

In the long run it would be nice to have a fancy resizable left column, e.g., as requested in #128.  I don't know how to do this and would need to look into the available Javascript libraries, so I don't have any current plans to work on that.
