### ISSUE TITLE
must-fail doesn't catch hard errors

### ISSUE THREAD

**Issue by jaredcdavis** [acl2/acl2#386]
I think it would be nice if the following worked:
```
(include-book "misc/eval" :dir :system)

(encapsulate ()
  (acl2::must-fail (value-triple (er hard? 'failure "this seems like a failure")))
  (defun f (x) x))

(f 3) ;; Desired result: 3.  Actual result: F is not defined
```

This would allow me to have quick tests that, e.g., extralogical run-time arity checking in SV is working correctly.  I imagine this is hard, because it would require `must-fail` to be able to catch/trap hard errors somehow.  This probably can't be done by user-level utilities.

**Comment by MattKaufmann** [comment]
This will probably (as suspected) require a significant ACL2 modification.  It might be much simpler to implement if trust tags can be involved; would that be OK?  Either way, I doubt I'll make any changes until my return in September, unless perhaps I'm told it's urgent.

**Comment by jaredcdavis** [comment]
It is definitely not urgent.  I can imagine that allowing user-level code to catch hard errors would be a major modification to ACL2.  Perhaps this is useful enough that we might consider whether you could build something like a top-level `must-cause-hard-error` form into ACL2 itself.  If that seems reasonably straightforward, I think it would be very nice to be able to write tests of this sort.

**Comment by MattKaufmann** [comment]
I've discussed this with J, and it looks like a potential "rat's nest".  So I'm closing this issue.  However, I'm open to discussion about alternatives, or even brow-beating to try to get me to reconsider.
