### ISSUE TITLE
An SVTV theorem I'm surprised to see fail

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#429]
I'm trying to figure out what the right way to work around this difference that occurs when ACL2 tries to match my checkpoint (which contains specific inputs to SVTV's that aren't from autoins) against the rule in the ACL2 database (which I wrote using autoins since that's easiest).  The following example is a simplified version of something I'm encountering on a real circuit.

The theorem that fails to prove is:

```
(thm
 (equal (svtv-run (my-svtv)
                 (my-svtv-autoins)
                 :skip nil
                 :boolvars t
                 :quiet nil)
       (svtv-run (my-svtv)
                 (list (cons 'a a)
                       (cons 'b b))
                 :skip nil
                 :boolvars t
                 :quiet nil)))
```

And here's the "expansions" related to determining the autoins.

```
ACL2 !>:trans1 (my-svtv-autoins)
 (MY-SVTV-AUTOINS-FN A B)
ACL2 !>(my-svtv-autoins-fn 'a 'b)
((A . A) (B . B))
ACL2 !>
```

The analog of the above theorem proves in Esim, most likely because there is no helper function akin to my-svtv-autoins-fn.  Maybe we should change the SV design to use the old style, where there is no helper function.  Or maybe the new style is important for reasons I haven't yet realized (after all, I'm still playing catch-up).  What do you think @solswords  @jaredcdavis ?

**Comment by ragerdl** [comment]
I've redone a little bit of my code, and I like the new approach of being able to pass in keyword values for the variables with values different from the defaults.  This also prevents the problem where the arguments to the `stv-run` call can have the same meaning but not match because the arguments were in a different order.

I'm going to experiment some more, but I expect to be a convert sometime soon.  One open question is whether there's a nice way to make it all work, even when you have to override each binding.

Also, perhaps it should be called `foo-svtv-ins` instead of `foo-svtv-autoins`.

**Comment by ragerdl** [comment]
Marking this as won't fix, since I think the autoins interface is pretty good and should be used.  I still think it should be renamed from `*autoins` to `*ins` since the interface is no longer optional, but that's a matter of opinion.

**Comment by solswords** [comment]
Not sure what you mean by "the interface is no longer optional" -- you can
still construct your own input alist however you like, the change is just
that autoins hides it inside a function instead of macroexpanding to a mess
of conses.  You could always write your own autoins macro if that's the
behavior you want.
