### ISSUE TITLE
coi/termination/assuming/complex.lisp broken on ACL2(hr) with CCL

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#435]
The following is a log, taken from the following build, which may change IP addresses int he future.  Regardless, the build is currently broken on ACL2(hr) with CCL.  I don't know who should fix it, but I'm setting it for the ACL2 7.2 milestone.

http://130.211.128.244/job/acl2-multi-everything/ACL2_HONS=h,ACL2_PAR=no_p,ACL2_REAL=r,LISP=ccl/5/console

   | Summary
   | Form:  ( INCLUDE-BOOK "arithmetic-5/top" ...)
   | Rules: NIL
   | Time:  0.95 seconds (prove: 0.00, print: 0.00, other: 0.94)
   | "/var/lib/jenkins/jobs/acl2-multi-everything/workspace/ACL2_HONS/h/ACL2_PAR/no_p/ACL2_REAL/r/LISP/ccl/books/arithmetic-5/top.lisp"
   | Goal'
   | Goal''
   | Goal'''
   | Goal'4'
   | Goal'5'
   | 
   | Summary
   | Form:  ( DEFTHM HACK0 ...)
   | Rules: ((:DEFINITION HIDE)
   |         (:DEFINITION NOT)
   |         (:FAKE-RUNE-FOR-TYPE-SET NIL)
   |         (:REWRITE |(* x (+ y z))|)
   |         (:REWRITE |(* y (* x z))|)
   |         (:REWRITE |(* y x)|))
   | Hint-events: ((:USE COMPLEX-DEFINITION)
   |               (:USE DISTRIBUTIVITY))
   | Time:  0.06 seconds (prove: 0.06, print: 0.00, other: 0.00)
   | Prover steps counted:  896
   | HACK0
   | Subgoal 2
   | Subgoal 2'
   | Subgoal 2''
   | 
   | Summary
   | Form:  ( DEFTHM REALPART-* ...)
   | Rules: ((:DEFINITION SYNP)
   |         (:ELIM REALPART-IMAGPART-ELIM)
   |         (:FAKE-RUNE-FOR-TYPE-SET NIL)
   |         (:REWRITE |(* y x)|)
   |         (:REWRITE DEFAULT-TIMES-1)
   |         (:REWRITE DEFAULT-TIMES-2))
   | Time:  0.02 seconds (prove: 0.01, print: 0.00, other: 0.00)
   | Prover steps counted:  378
   | 
   | ---
   | The key checkpoint goal, below, may help you to debug this failure.
   | See :DOC failure and see :DOC set-checkpoint-summary-limit.
   | ---
   | 
   | *** Key checkpoint before reverting to proof by induction: ***
   | 
   | Subgoal 2
   | (IMPLIES (AND (RATIONALP Y) (ACL2-NUMBERP X))
   |          (EQUAL (REALPART (* X Y))
   |                 (* Y (REALPART X))))
   | 
   | ACL2 Error in ( DEFTHM REALPART-* ...):  See :DOC failure.
   | 
   | ******** FAILED ********
   | 
   | Summary
   | Form:  ( ENCAPSULATE NIL (LOCAL ...) ...)
   | Rules: NIL
   | Time:  0.08 seconds (prove: 0.08, print: 0.00, other: 0.00)
   | Prover steps counted:  1274
   | 
   | ACL2 Error in ( ENCAPSULATE NIL (LOCAL ...) ...):  See :DOC failure.
   | 
   | ******** FAILED ********
   | 
   | Summary
   | Form:  (CERTIFY-BOOK "complex" ...)
   | Rules: NIL
   | Time:  2.48 seconds (prove: 0.16, print: 0.01, other: 2.31)
   | Prover steps counted:  13023
   | 
   | ACL2 Error in (CERTIFY-BOOK "complex" ...):  See :DOC failure.
   | 
   | ******** FAILED ********
   | ; (EV-REC *RETURN-LAST-ARG3* ...) took 
   | ; 2.48 seconds realtime, 2.47 seconds runtime
   | ; (186,797,088 bytes allocated).
   | ACL2(r) !>Bye.
   | Exit code from ACL2 is 0
   | complex.cert seems to be missing

**Comment by MattKaufmann** [comment]
Thanks, David.  I don't know who broke ACL2(r) but the failure is in
the book mentioned on your subject line (I didn't see it in your
message, so I am repeating it here):

make[1]: *** [coi/termination/assuming/complex.cert] Error 1

I wonder if someone changed arithmetic-5 recently in a way that had
this adverse affect for ACL2(r).  If so, I hope they'll fix it....

Thanks --
-- Matt
   Date: Tue, 07 Jul 2015 10:09:24 -0700
   From: "David L. Rager" <notifications@github.com>
   Reply-To: acl2/acl2 <reply@reply.github.com>
   The following is a log, taken from the following build, which may change IP addresses int he future.  Regardless, the build is currently broken on ACL2(hr) with CCL.  I don't know who should fix it, but I'm setting it for the ACL2 7.2 milestone.

   http://130.211.128.244/job/acl2-multi-everything/ACL2_HONS=h,ACL2_PAR=no_p,ACL2_REAL=r,LISP=ccl/5/console

      | Summary
      | Form:  ( INCLUDE-BOOK "arithmetic-5/top" ...)
      | Rules: NIL
      | Time:  0.95 seconds (prove: 0.00, print: 0.00, other: 0.94)
      | "/var/lib/jenkins/jobs/acl2-multi-everything/workspace/ACL2_HONS/h/ACL2_PAR/no_p/ACL2_REAL/r/LISP/ccl/books/arithmetic-5/top.lisp"
      | Goal'
      | Goal''
      | Goal'''
      | Goal'4'
      | Goal'5'
      | 
      | Summary
      | Form:  ( DEFTHM HACK0 ...)
      | Rules: ((:DEFINITION HIDE)
      |         (:DEFINITION NOT)
      |         (:FAKE-RUNE-FOR-TYPE-SET NIL)
      |         (:REWRITE |(* x (+ y z))|)
      |         (:REWRITE |(* y (* x z))|)
      |         (:REWRITE |(* y x)|))
      | Hint-events: ((:USE COMPLEX-DEFINITION)
      |               (:USE DISTRIBUTIVITY))
      | Time:  0.06 seconds (prove: 0.06, print: 0.00, other: 0.00)
      | Prover steps counted:  896
      | HACK0
      | Subgoal 2
      | Subgoal 2'
      | Subgoal 2''
      | 
      | Summary
      | Form:  ( DEFTHM REALPART-* ...)
      | Rules: ((:DEFINITION SYNP)
      |         (:ELIM REALPART-IMAGPART-ELIM)
      |         (:FAKE-RUNE-FOR-TYPE-SET NIL)
      |         (:REWRITE |(* y x)|)
      |         (:REWRITE DEFAULT-TIMES-1)
      |         (:REWRITE DEFAULT-TIMES-2))
      | Time:  0.02 seconds (prove: 0.01, print: 0.00, other: 0.00)
      | Prover steps counted:  378
      | 
      | ---
      | The key checkpoint goal, below, may help you to debug this failure.
      | See :DOC failure and see :DOC set-checkpoint-summary-limit.
      | ---
      | 
      | *** Key checkpoint before reverting to proof by induction: ***
      | 
      | Subgoal 2
      | (IMPLIES (AND (RATIONALP Y) (ACL2-NUMBERP X))
      |          (EQUAL (REALPART (* X Y))
      |                 (* Y (REALPART X))))
      | 
      | ACL2 Error in ( DEFTHM REALPART-* ...):  See :DOC failure.
      | 
      | ******** FAILED ********
      | 
      | Summary
      | Form:  ( ENCAPSULATE NIL (LOCAL ...) ...)
      | Rules: NIL
      | Time:  0.08 seconds (prove: 0.08, print: 0.00, other: 0.00)
      | Prover steps counted:  1274
      | 
      | ACL2 Error in ( ENCAPSULATE NIL (LOCAL ...) ...):  See :DOC failure.
      | 
      | ******** FAILED ********
      | 
      | Summary
      | Form:  (CERTIFY-BOOK "complex" ...)
      | Rules: NIL
      | Time:  2.48 seconds (prove: 0.16, print: 0.01, other: 2.31)
      | Prover steps counted:  13023
      | 
      | ACL2 Error in (CERTIFY-BOOK "complex" ...):  See :DOC failure.
      | 
      | ******** FAILED ********
      | ; (EV-REC *RETURN-LAST-ARG3* ...) took 
      | ; 2.48 seconds realtime, 2.47 seconds runtime
      | ; (186,797,088 bytes allocated).
      | ACL2(r) !>Bye.
      | Exit code from ACL2 is 0
      | complex.cert seems to be missing

   ---
   Reply to this email directly or view it on GitHub:
   https://github.com/acl2/acl2/issues/435

**Comment by ragerdl** [comment]
Matt's emailed Ruben, but we haven't heard back from him.  @nadezhin would you mind taking a look?

**Comment by ragerdl** [comment]
Ah ha, @nadezhin reports that this book (`complex.lisp`) recently became enabled in the ACL2(r) everything build, because a book that it depends on is now certifiable with ACL2(r).  I think the simplest thing to do is mark is as non-acl2r with `;; cert_param: (non-acl2r)`, so I'll do that.

**Comment by ragerdl** [comment]
@nadezhin made this book certifiable in c97956d27c4b45f1eece613c470427b68deb54f6
