### ISSUE TITLE
projects/x86isa/portcullis/syscall-numbers.lisp broken on ACL2(c) with GCL

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#436]
The following is a log, taken from the following build, which may change IP addresses in the future. Regardless, the build is currently broken on ACL2(c) with GCL. I'm filing it against Shilpi since she maintains the X86 books.  I'm also setting it for the ACL2 7.2 milestone.

http://130.211.128.244/job/acl2-multi-everything/ACL2_HONS=no_h,ACL2_PAR=no_p,ACL2_REAL=no_r,LISP=gcl/5/console

   | ACL2 !> "ACL2"
   | ACL2 !> (:EXIT 1)
   | ACL2 !> (PROVE PROOF-TREE
   |         WARNING OBSERVATION EVENT HISTORY)
   | ACL2 !> T
   | ACL2 !>NIL
   | ACL2 !> :IGNORED
   | ACL2 !>
   | Loading /var/lib/jenkins/jobs/acl2-multi-everything/workspace/ACL2_HONS/no_h/ACL2_PAR/no_p/ACL2_REAL/no_r/LISP/gcl/books/projects/x86isa/portcullis/portcullis.o
   | Loading /var/lib/jenkins/jobs/acl2-multi-everything/workspace/ACL2_HONS/no_h/ACL2_PAR/no_p/ACL2_REAL/no_r/LISP/gcl/books/centaur/bitops/portcullis.o
   | Loading /var/lib/jenkins/jobs/acl2-multi-everything/workspace/ACL2_HONS/no_h/ACL2_PAR/no_p/ACL2_REAL/no_r/LISP/gcl/books/std/portcullis.o
   | start address -T 0x28e3050 Finished loading /var/lib/jenkins/jobs/acl2-multi-everything/workspace/ACL2_HONS/no_h/ACL2_PAR/no_p/ACL2_REAL/no_r/LISP/gcl/books/std/portcullis.o
   | start address -T 0xf85640 Finished loading /var/lib/jenkins/jobs/acl2-multi-everything/workspace/ACL2_HONS/no_h/ACL2_PAR/no_p/ACL2_REAL/no_r/LISP/gcl/books/centaur/bitops/portcullis.o
   | start address -T 0xf175c0 Finished loading /var/lib/jenkins/jobs/acl2-multi-everything/workspace/ACL2_HONS/no_h/ACL2_PAR/no_p/ACL2_REAL/no_r/LISP/gcl/books/projects/x86isa/portcullis/portcullis.o
   | [SGC for 12 SYMBOL pages..(75 faulted pages, 76568 writable, 11850 read only)..(T=2).GC finished]
   | 
   | Summary
   | Form:  ( INCLUDE-BOOK "portcullis" ...)
   | Rules: NIL
   | Time:  1.49 seconds (prove: 0.00, print: 0.00, other: 1.49)
   |  "/var/lib/jenkins/jobs/acl2-multi-everything/workspace/ACL2_HONS/no_h/ACL2_PAR/no_p/ACL2_REAL/no_r/LISP/gcl/books/projects/x86isa/portcullis/portcullis.lisp"
   | ACL2 !> T
   | ACL2 !> :CONTINUE
   | ACL2 !>[SGC off][GC for 58952 RELOCATABLE-BLOCKS pages..(T=9).GC finished]
   | [SGC on]
   | 
   | ACL2 Error in ( DEFMACRO OS ...):  Defmacro requires at least 3 arguments.
   | (DEFMACRO OS (L D)) is ill-formed.  See :DOC defmacro.
   | 
   | 
   | Summary
   | Form:  ( DEFMACRO OS ...)
   | Rules: NIL
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | 
   | ACL2 Error in ( DEFMACRO OS ...):  See :DOC failure.
   | 
   | ******** FAILED ********
   | 
   | Summary
   | Form:  (CERTIFY-BOOK "syscall-numbers" ...)
   | Rules: NIL
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | 
   | ACL2 Error in (CERTIFY-BOOK "syscall-numbers" ...):  See :DOC failure.
   | 
   | ******** FAILED ********
   | ; (EV-REC *RETURN-LAST-ARG3* ...) took 
   | ; 0.00 seconds realtime,
   | ; 0.00 seconds runtime, 0.00 seconds child runtime,
   | ; 0.00 seconds systime, 0.00 seconds child systime.
   | ACL2 !>Bye.
   | Exit code from ACL2 is 0
   | syscall-numbers.cert seems to be missing

**CERTIFICATION FAILED** for /var/lib/jenkins/jobs/acl2-multi-everything/workspace/ACL2_HONS/no_h/ACL2_PAR/no_p/ACL2_REAL/no_r/LISP/gcl/books/projects/x86isa/portcullis/syscall-numbers.lisp

**Comment by ragerdl** [comment]
@shigoel or @myall86 Do you mind adding a cert_param that indicates the x86 book can't be built on GCL?  If you want to push back or have a philosophical reason that you don't want to maintain books on GCL, lmk!

```
; cert_param: (non-gcl)
```

**Comment by MattKaufmann** [comment]
Hi, David

Here are comments, perhaps already obvious, on the following:

>> philosophical reason that you don't want to maintain books on GCL

I see a balance to be struck between supporting everything possible on
all supported Lisps, and not going to excessive trouble in order to
make that happen.  In the current case, I wonder if there's an easy
way to continue to certify the x86 books in GCL but avoid whatever
particular problem concerns GCL there.

-- Matt
   Date: Sat, 25 Jul 2015 08:26:04 -0700
   From: "David L. Rager" <notifications@github.com>
   Reply-To: acl2/acl2 <reply@reply.github.com>

   @shigoel or @myall86 Do you mind adding a cert_param that indicates the x86 book can't be built on GCL?  If you want to push back or have a philosophical reason that you don't want to maintain books on GCL, lmk!

   ```
   ; cert_param: (non-gcl)
   ```



   ---
