### ISSUE TITLE
:doc auto-bindings potential bug?

### ISSUE THREAD

**Issue by pennyan** [acl2/acl2#459]
In the example,
(def-gl-thm foo
  ...
  :g-bindings (auto-bindings               ; expands to:
               (:nat opcode 8)             ; g-number with indices 0-8
               (:int multiplier 16)        ; g-number with indices 9-25
               (:bool enable)              ; g-boolean with index 26
               (:mix (:nat a-bus 128)      ; }  g-numbers whose indicies
                     (:nat b-bus 128)      ; }  are interleaved, 27 to 414
                     (:nat c-bus 128))     ; }
               (:nat fixup-bits 4)         ; g-number with indices 415-420
               ))

Could it be that the ranges in the comments should really be:
; g-number with indices 0 - 7
; g-number with indices 8 - 23
; ....
?

**Comment by jaredcdavis** [comment]
I think the current comments are right, but only for a subtle reason --
GL's representation of integers is signed, so if you want to be able to
represent any 8-bit natural, you need 9 bits, etc.

On Fri, Jul 17, 2015 at 3:32 PM, pennyan <notifications@github.com> wrote:

> In the example,
> (def-gl-thm foo
> ...
> :g-bindings (auto-bindings ; expands to:
> (:nat opcode 8) ; g-number with indices 0-8
> (:int multiplier 16) ; g-number with indices 9-25
> (:bool enable) ; g-boolean with index 26
> (:mix (:nat a-bus 128) ; } g-numbers whose indicies
> (:nat b-bus 128) ; } are interleaved, 27 to 414
> (:nat c-bus 128)) ; }
> (:nat fixup-bits 4) ; g-number with indices 415-420
> ))
>
> Could it be that the ranges in the comments should really be:
> ; g-number with indices 0 - 7
> ; g-number with indices 8 - 23
> ; ....
> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acl2/acl2/issues/459>.
>



-- 
Jared C. Davis <jared@cs.utexas.edu>
11410 Windermere Meadows
Austin, TX 78759
http://www.cs.utexas.edu/users/jared/

**Comment by ragerdl** [comment]
Indeed, at least the first couple are correct so I'll go ahead and close this.
