### ISSUE TITLE
LispWorks error during certification of books/std/bitsets/bignum-extract-opt.lisp

### ISSUE THREAD

**Issue by MattKaufmann** [acl2/acl2#460]
Running ACL2 built on LispWorks in directory
books/std/bitsets/, I got a Lisp error as shown
just below; explanation follows.

    BITSETS !>(ld "bignum-extract-opt.lisp")

    .....

    BITSETS !>>>(ASSERT! (TEST2 *TEST-NUMBERS* *TEST-SLICE-INDICES*))

    ***********************************************
    ************ ABORTING from raw Lisp ***********
    Error:  Arithmetic error in BYTE of (32 72057594037927936): Argments must both be fixnums in range [0,LOW64::*MAX-BYTE-SIZE*)..
    ***********************************************

Ultimately, the problem is with the following
definition from file bignum-extract-opt-raw.lsp in
that directory.

    (defun bignum-extract (x slice)

      ;; Simple Lisp version for most Lisps.
      #-(and Clozure x86-64)
      (the (unsigned-byte 32)
	   (ldb (byte 32 (* 32 slice)) x))
      ....)

Specifically, if you redefine this function by
adding a suitable print statement, you'll see a
call of ldb that can be made to cause the error:

    ACL2 1 > (let ((x 1) (slice 2251799813685248))
		(ldb (byte 32 (* 32 slice)) x))

    Error: Arithmetic error in BYTE of (32 72057594037927936): Argments must both be fixnums in range [0,LOW64::*MAX-BYTE-SIZE*)..
      1 (continue) Return a value to use.
      2 (abort) Return to level 0.
      3 Restart top-level loop.

    Type :b for backtrace or :c <option number> to proceed.
    Type :bug-form "<subject>" for a bug report template or :? for other options.

    ACL2 2 : 1 > 

Unfortunately, the LispWorks error seems
confusing, since there seems to be no variable
LOW64::*MAX-BYTE-SIZE* or anything I could find
like it (using apropos).

I'd be happy to report this to LispWorks if I'm
told that would be appropriate (I haven't looked
at ldb).  In the meantime, it would probably be
good to have some sort of fix that allows
LispWorks-based regressions to pass.

**Comment by jaredcdavis** [comment]
Hi,

This looks like a Lispworks error: Common Lisp says that [byte](http://clhs.lisp.se/Body/f_by_by.htm#byte) takes non-negative integers, not fixnums.  SBCL has a [similar bug](https://bugs.launchpad.net/sbcl/+bug/963330).

A temporary workaround might be to change the `#-sbcl` calls in:

    std/bitsets/bignum-extract-opt-raw.lsp
    std/bitsets/bitsets-opt-raw.lsp

To something like `#+(and (not sbcl) (not lispworks))`.  Alternately we could just mark the book as non-lispworks, but that may remove several books from its regression.

Cheers,
Jared

**Comment by MattKaufmann** [comment]
OK, thanks; I'm making the suggested change, and will check it in after regression.

I've emailed LIspWorks Support about the bug.

**Comment by jaredcdavis** [comment]
Sounds great -- thanks for taking care of it!

On Mon, Jul 20, 2015 at 12:10 PM, MattKaufmann <notifications@github.com>
wrote:

> OK, thanks; I'm making the suggested change, and will check it in after
> regression.
>
> I've emailed LIspWorks Support about the bug.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acl2/acl2/issues/460#issuecomment-122955444>.
>



-- 
Jared C. Davis <jared@cs.utexas.edu>
11410 Windermere Meadows
Austin, TX 78759
http://www.cs.utexas.edu/users/jared/

**Comment by MattKaufmann** [comment]
Closing with commit b23f94908d2c5b160ca470316baea38479ef9696.
