### ISSUE TITLE
:puff crashes

### ISSUE THREAD

**Issue by ericsmithkestrel** [acl2/acl2#470]
The following seems to crash things in a new ACL2 session (note: I don't really use :puff, so this is not high priority for me).

(include-book "coi/lists/basic" :dir :system)
:puff 1

**Comment by MattKaufmann** [comment]
I plan to consider modifying :puff for include-book to execute the portcullis commands, which would likely fix this problem.  But it may not happen for a month or two unless someone emails me directly.

**Comment by MattKaufmann** [comment]
Fixed on 9/8/2015 with commit 686c4226218efa576e4fb1588e1e3f94b28ce5b6.
