### ISSUE TITLE
escape characters in regression logs

### ISSUE THREAD

**Issue by MattKaufmann** [acl2/acl2#472]
Sometime between July 19 and July 24 there was a
change that now causes, in regression logs, escape
characters (#\ESC, char-code 27) to appear near
the beginning and end of seemingly every line that
starts with "Built", and formerly started with
"Successfully built".  Any idea why or, better
yet, can someone fix this?  This is probably not
too important, but could make it more awkward to
send log snippets via email.

**Comment by jaredcdavis** [comment]
Hi,

It's because of this:

https://github.com/acl2/acl2/commit/c08018a27ab373e6bd6a5009f7b9fc9c12199af5

It should be easy to turn off by exporting CERT_PL_NO_COLOR=1 if you don't
like it.

Cheers,
Jared

On Thu, Jul 30, 2015 at 2:08 PM, MattKaufmann <notifications@github.com>
wrote:

> Sometime between July 19 and July 24 there was a
> change that now causes, in regression logs, escape
> characters (#\ESC, char-code 27) to appear near
> the beginning and end of seemingly every line that
> starts with "Built", and formerly started with
> "Successfully built". Any idea why or, better
> yet, can someone fix this? This is probably not
> too important, but could make it more awkward to
> send log snippets via email.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acl2/acl2/issues/472>.
>



-- 
Jared C. Davis <jared@cs.utexas.edu>
11410 Windermere Meadows
Austin, TX 78759
http://www.cs.utexas.edu/users/jared/

**Comment by ragerdl** [comment]
BTW, if it doesn't show up for you in your Emacs shell mode, you might try messing
with things like ansi-color-for-comint-mode-on and perhaps font-lock-mode.

**Comment by ragerdl** [comment]
I think something like the following stands a decent shot at working so long as you start from a fresh emacs:

```
(add-hook 'shell-mode-hook 'ansi-color-for-comint-mode-on)
```

**Comment by MattKaufmann** [comment]
I don't see why this is the default for a log file that probably should be redirected to a file, but OK.
I've reopened this issue because I don't see this environment variable documented anywhere, or any occurrence of "color" or "escape" under CERT.PL -- so now it's a documentation issue.

**Comment by jaredcdavis** [comment]
We could perhaps disable color when stdout is being redirected to a non-terminal.

OTOH, it's nice to have color coded output in Jenkins logs such as this:
    http://leeroy.defthm.com/job/acl2-testing/70/console

Aside from looking a bit funny, I would not expect these color codes to cause any problems.  If they do and an environment variable is insufficient for some reason, we can certainly reconsider...

**Comment by ragerdl** [comment]
I added the following so that emacs would open my .log files with ansi-color enabled by default.  We should probably add this to the documentation if it's not there already:

```
(defun ansi-color-apply-on-region-int (beg end)
  "interactive version of func"
  (interactive "r")
  (ansi-color-apply-on-region beg end))

(define-derived-mode fundamental-ansi-mode fundamental-mode "fundamental ansi"
  "Fundamental mode that understands ansi colors."
  (require 'ansi-color)
  (ansi-color-apply-on-region (point-min) (point-max)))

(setq auto-mode-alist
      (cons '("\\.log\\'" . fundamental-ansi-mode) auto-mode-alist))
```
