### ISSUE TITLE
Fix missing book for rtl bvecp-helper.lisp

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#479]
In the `testing` branch of the repository, I'm getting the following warning, which prevents the building of rtl rel11.  @nadezhin could you please have a look and recommend a fix?

Warning: missing file rtl/rel11/rel9-rtl-pkg/support/lib1/rtlarr.lisp (required by rtl/rel11/rel9-rtl-pkg/support/lib1/bvecp-helpers.lisp)

**Comment by nadezhin** [comment]
The fix is in the https://github.com/nadezhin/acl2/commit/7da88ee3a407434965b9fa88e9b89d9ec3f4c272 .
Remove missing `(include-book "rtlarr")`

**Comment by ragerdl** [comment]
This is fixed.  Thanks again for the report @russinoff  and fix @nadezhin .
