### ISSUE TITLE
manual build is broken

### ISSUE THREAD

**Issue by MattKaufmann** [acl2/acl2#485]
A moment ago I tried to build the acl2+books manual in the
same way as I've done many times before, but it failed, at
least partially.  You can see the result by looking at

http://www.cs.utexas.edu/users/moore/acl2/manuals/bad/2015-08-13/manual/?topic=ACL2____TOP

-- clearly a lot of text is missing.  As the pathname above
might suggest, I moved the bad (new) manual after generating
it; then I restored the old one.  I won't update the
"bleeding edge" manual again
(http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index.html)
until this issue is fixed.

A log is below, where the first error is
"Can't locate JSON/XS.pm in @INC....".

..... full log .....

    eld:/projects/acl2/acl2% git status
    On branch master
    Your branch is up-to-date with 'origin/master'.
    Untracked files:
      (use "git add <file>..." to include in what will be committed)

	    books/temp/
	    tmp.msg

    nothing added to commit but untracked files present (use "git add" to track)
    eld:/projects/acl2/acl2% bin/make-fancy-manual.sh 
    mkdir /u/www/users/moore/acl2/manuals/2015-08-13
    /projects/acl2/acl2/books/doc/manual /projects/acl2/acl2
    Can't locate JSON/XS.pm in @INC (you may need to install the JSON::XS module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at xdata2sql.pl line 36.
    BEGIN failed--compilation aborted at xdata2sql.pl line 36.
    Can't locate JSON/XS.pm in @INC (you may need to install the JSON::XS module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at ./xdata2sql4seo.pl line 33.
    BEGIN failed--compilation aborted at ./xdata2sql4seo.pl line 33.
    chmod: cannot access ?./xdata-seo.db?: No such file or directory
    chmod: cannot access ?xdata.db?: No such file or directory
    /projects/acl2/acl2
    cp -pr /projects/acl2/acl2/books/doc/manual /u/www/users/moore/acl2/manuals/2015-08-13/manual
    cd /u/www/users/moore/acl2/manuals/2015-08-13/manual
    perl xdata2sql.pl
    Can't locate JSON/XS.pm in @INC (you may need to install the JSON::XS module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at xdata2sql.pl line 36.
    BEGIN failed--compilation aborted at xdata2sql.pl line 36.
    chmod +x xdataget.pl
    ln -s xdataget.pl xdataget.cgi
    cp -p /projects/acl2/acl2/books/system/doc/rendered-doc-combined.lsp /u/www/users/moore/acl2/manuals/2015-08-13/
    gzip /u/www/users/moore/acl2/manuals/2015-08-13/rendered-doc-combined.lsp
    Running ./update.sh 2015-08-13 in directory /u/www/users/moore/acl2/manuals
    New recent = 2015-08-13
    New previous = 2015-08-09
    Obsolete = 2015-08-08
    eld:/projects/acl2/acl2%

**Comment by jaredcdavis** [comment]
Hi,

It looks like your copy of Perl is missing the json::xs module.  Probably
your network admins have upgraded Perl and not installed this module.  It
should be very easy for them to install it, if you let them know that you
need it.

Cheers,
Jared

On Thu, Aug 13, 2015 at 1:58 AM, MattKaufmann <notifications@github.com>
wrote:

> A moment ago I tried to build the acl2+books manual in the
> same way as I've done many times before, but it failed, at
> least partially. You can see the result by looking at
>
>
> http://www.cs.utexas.edu/users/moore/acl2/manuals/bad/2015-08-13/manual/?topic=ACL2____TOP
>
> -- clearly a lot of text is missing. As the pathname above
> might suggest, I moved the bad (new) manual after generating
> it; then I restored the old one. I won't update the
> "bleeding edge" manual again
> (
> http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index.html
> )
> until this issue is fixed.
>
> A log is below, where the first error is
> "Can't locate JSON/XS.pm in @INC <https://github.com/INC>....".
>
> ..... full log .....
>
> eld:/projects/acl2/acl2% git status
> On branch master
> Your branch is up-to-date with 'origin/master'.
> Untracked files:
>   (use "git add <file>..." to include in what will be committed)
>
>     books/temp/
>     tmp.msg
>
> nothing added to commit but untracked files present (use "git add" to track)
> eld:/projects/acl2/acl2% bin/make-fancy-manual.sh
> mkdir /u/www/users/moore/acl2/manuals/2015-08-13
> /projects/acl2/acl2/books/doc/manual /projects/acl2/acl2
> Can't locate JSON/XS.pm in @INC (you may need to install the JSON::XS module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at xdata2sql.pl line 36.
> BEGIN failed--compilation aborted at xdata2sql.pl line 36.
> Can't locate JSON/XS.pm in @INC (you may need to install the JSON::XS module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at ./xdata2sql4seo.pl line 33.
> BEGIN failed--compilation aborted at ./xdata2sql4seo.pl line 33.
> chmod: cannot access ?./xdata-seo.db?: No such file or directory
> chmod: cannot access ?xdata.db?: No such file or directory
> /projects/acl2/acl2
> cp -pr /projects/acl2/acl2/books/doc/manual /u/www/users/moore/acl2/manuals/2015-08-13/manual
> cd /u/www/users/moore/acl2/manuals/2015-08-13/manual
> perl xdata2sql.pl
> Can't locate JSON/XS.pm in @INC (you may need to install the JSON::XS module) (@INC contains: /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at xdata2sql.pl line 36.
> BEGIN failed--compilation aborted at xdata2sql.pl line 36.
> chmod +x xdataget.pl
> ln -s xdataget.pl xdataget.cgi
> cp -p /projects/acl2/acl2/books/system/doc/rendered-doc-combined.lsp /u/www/users/moore/acl2/manuals/2015-08-13/
> gzip /u/www/users/moore/acl2/manuals/2015-08-13/rendered-doc-combined.lsp
> Running ./update.sh 2015-08-13 in directory /u/www/users/moore/acl2/manuals
> New recent = 2015-08-13
> New previous = 2015-08-09
> Obsolete = 2015-08-08
> eld:/projects/acl2/acl2%
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acl2/acl2/issues/485>.
>



-- 
Jared C. Davis <jared@cs.utexas.edu>
11410 Windermere Meadows
Austin, TX 78759
http://www.cs.utexas.edu/users/jared/

**Comment by MattKaufmann** [comment]
Thanks, Jared; the sysadmins have installed a module that fixes the problem.
