### ISSUE TITLE
Cleanup `must-fail'`s output

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#525]
It'd be nice if `must-fail` didn't print the additional ~10 lines of output at its end, but instead printed something like `Event failed as it was supposed to`.

And to go the extra mile, if it's a `must-fail` of an `assert!`, that we wouldn't get a long message that explained the assertion failure in long form.  Maybe the answer is a primitive named `assert-not`, `assert-fail`, `assert-false`, or `assert-nil`.  Does that already exist?

I'll throw this on the wishlist.

Motivating example:
```
ACL2 !>(must-fail (assert! (equal t nil)))


ACL2 Error in ASSERT!:  Assertion failed:
(EQUAL T NIL)



ACL2 Error in ( MAKE-EVENT (LET ...) ...):  Error in MAKE-EVENT on
behalf of
  (ASSERT! (EQUAL T NIL))
from expansion of:
  (LET ((ASSERTION (EQUAL T NIL)))
       (ER-PROGN (IF ASSERTION (VALUE NIL)
                     (ER SOFT 'ASSERT!
                         "Assertion failed:~%~x0" '#))
                 (VALUE '(VALUE-TRIPLE :SUCCESS))))
(See :DOC set-iprint to be able to see elided values in this message.)


Summary
Form:  ( MAKE-EVENT (LET ...) ...)
Rules: NIL
Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)

ACL2 Error in ( MAKE-EVENT (LET ...) ...):  See :DOC failure.

******** FAILED ********

Summary
Form:  ( MAKE-EVENT (STATE-GLOBAL-LET* ...) ...)
Rules: NIL
Time:  0.01 seconds (prove: 0.00, print: 0.00, other: 0.01)

Summary
Form:  ( MAKE-EVENT (QUOTE ...) ...)
Rules: NIL
Time:  0.01 seconds (prove: 0.00, print: 0.00, other: 0.01)
 T
ACL2 !>
```

I'd prefer that it just say
```
ACL2 !>(must-fail (assert! (equal t nil)))


ACL2 Error in MUST-FAIL and ASSERT!:  As expected, assertion failed:
(EQUAL T NIL)

ACL2 !>
```

**Comment by MattKaufmann** [comment]
Fixed (at least, to work as I think makes sense) in commit 41c713c8150d9fc19fe094054e363d5e94a606e0

**Comment by ragerdl** [comment]
As discussed with Matt, it might be worth using the :push and :pop feature to save the feedback from `assert!` when surrounded by a `must-fail`, but we'll wait for another day to explore that.  Thanks for the fix Matt!

**Comment by MattKaufmann** [comment]
Hi, David --

Right, I was thinking that :push and :pop might be useful.  But
actually, the following example, based on the one you originally sent
me, illustrates that it is now reasonably straightforward to obtain
desired behavior from must-fail.  First we evaluate these:

(include-book "misc/eval" :dir :system)
(include-book "misc/assert" :dir :system)
(defmacro must-fail-assert! (assertion
                             &key form (return-value ':invisible))
  `(with-output :off (event summary)
     (progn (must-fail (assert! ,assertion ,form))
            (value-triple (prog2$
                           (cw "As expected, assertion ~x0 failed.~|"
                               ',assertion)
                           ,return-value)))))

Then we have this log for your example.

ACL2 !>(must-fail-assert! (equal t nil))
As expected, assertion (EQUAL T NIL) failed.
ACL2 !>(must-fail-assert! (equal t nil) :return-value :success)
As expected, assertion (EQUAL T NIL) failed.
 :SUCCESS
ACL2 !>

-- Matt
