### ISSUE TITLE
Curve lemma is time-consuming

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#580]
It's not critical, but there's one lemma in the elliptic curve book that's pretty slow.  Can it be sped up with minimal effort?  It's probably low-hanging fruit in terms of making our regression faster (it makes the book ten minutes).  It might be as simple as disabling the pre-processor.  Accumulated-persistence and dmr-mode could also help.

```
Subgoal 2
Subgoal 1

Summary
Form:  ( DEFTHM ECP-TERM-FRCP-12 ...)
Rules: ((:COMPOUND-RECOGNIZER ACL2::NATP-COMPOUND-RECOGNIZER)
        (:DEFINITION DX)
        (:DEFINITION EVAL3$)
        (:DEFINITION F*)
        (:DEFINITION F+)
        (:DEFINITION F/)
        (:DEFINITION FEXPT)
        (:DEFINITION LEN)
        (:DEFINITION MOD-EXPT)
        (:DEFINITION NOT)
        (:DEFINITION SYNP)
        (:DEFINITION TRIPP$)
        (:DEFINITION TRUE-LISTP)
        (:EXECUTABLE-COUNTERPART <)
        (:EXECUTABLE-COUNTERPART A)
        (:EXECUTABLE-COUNTERPART BINARY-*)
        (:EXECUTABLE-COUNTERPART BINARY-+)
        (:EXECUTABLE-COUNTERPART CAR)
        (:EXECUTABLE-COUNTERPART CDR)
        (:EXECUTABLE-COUNTERPART CONSP)
        (:EXECUTABLE-COUNTERPART EQUAL)
        (:EXECUTABLE-COUNTERPART LEN)
        (:EXECUTABLE-COUNTERPART NOT)
        (:EXECUTABLE-COUNTERPART POLYP$)
        (:FAKE-RUNE-FOR-LINEAR NIL)
        (:FAKE-RUNE-FOR-TYPE-SET NIL)
        (:REWRITE ACL2::|(* (* x y) z)|)
        (:REWRITE ACL2::|(* y (* x z))|)
        (:REWRITE ACL2::|(* y x)|)
        (:REWRITE ACL2::|(+ c (+ d x))|)
        (:REWRITE ACL2::|(+ y (+ x z))|)
        (:REWRITE ACL2::|(+ y x)|)
        (:REWRITE ACL2::|(expt (* x y) n)|)
        (:REWRITE ACL2::|(expt (expt x m) n)|)
        (:REWRITE CAR-CONS-OPEN)
        (:REWRITE CDR-CONS-OPEN)
        (:REWRITE ACL2::DEFAULT-MOD-RATIO)
        (:REWRITE FRCP-EXPT)
        (:REWRITE MOD*REWRITE-2)
        (:REWRITE MOD+REWRITE-2)
        (:REWRITE MOD+REWRITE-3)
        (:REWRITE MOD-EXPT-REWRITE)
        (:TYPE-PRESCRIPTION ACL2::EXPT-TYPE-PRESCRIPTION-INTEGERP-BASE)
        (:TYPE-PRESCRIPTION ACL2::EXPT-TYPE-PRESCRIPTION-NONNEGATIVE-BASE)
        (:TYPE-PRESCRIPTION INTEGERP-EVALP$)
        (:TYPE-PRESCRIPTION ACL2::INTEGERP-MOD-1)
        (:TYPE-PRESCRIPTION LEN)
        (:TYPE-PRESCRIPTION NATP-FRCP)
        (:TYPE-PRESCRIPTION P-NAT)
        (:TYPE-PRESCRIPTION POLYP$)
        (:TYPE-PRESCRIPTION ACL2::RATIONALP-MOD))
Hint-events: ((:USE ECP-TERM-FRCP-11))
Time:  543.36 seconds (prove: 543.36, print: 0.00, other: 0.00)
Prover steps counted:  32186
(:DEFTHMD ECP-TERM-FRCP-12)
```

**Comment by ragerdl** [comment]
Sorry I forgot to say that this is in book:

`books/projects/curve25519/terms.lisp`

**Comment by MattKaufmann** [comment]
I was thinking of simply arranging that projects/curve25519/ is
skipped except by "regression-everything".  Comments, David R. or
David R. or any other David or...?

-- Matt

**Comment by ragerdl** [comment]
Well, that's simpler, but it still means the regression that we use to gate changes is slow.  I happen to be caring about that time today, so I've made a note.  Note that others may feel free to disregard my note.

**Comment by MattKaufmann** [comment]
Hi, David --

Sorry, I don't understand.  By "regression that we use to gate
changes" do you mean that the automated testing you're orchestrating
does "regression-everything"?

-- Matt

**Comment by ragerdl** [comment]
Hi Matt,

Well, that's what I meant, but....  upon further inspection, it's not easy
for me to determine which target I'm actually building....  it looks like
it's building "all", but I'm a little surprised.  Also, this book should
really continue to be part of the "gatekeeper", because the community is
making lots of changes to the RTL library, which I think is required for
that book.

David

**Comment by jaredcdavis** [comment]
I took a quick look at this today and it looks easy to speed it up a lot.
I'll commit something tomorrow (just some kind of in-theory change).

On Mon, Jan 25, 2016 at 6:21 PM, David L. Rager <notifications@github.com>
wrote:

> Hi Matt,
>
> Well, that's what I meant, but.... upon further inspection, it's not easy
> for me to determine which target I'm actually building.... it looks like
> it's building "all", but I'm a little surprised. Also, this book should
> really continue to be part of the "gatekeeper", because the community is
> making lots of changes to the RTL library, which I think is required for
> that book.
>
> David
>
> On Mon, Jan 25, 2016 at 5:07 PM, MattKaufmann <notifications@github.com>
> wrote:
>
> > Hi, David --
> >
> > Sorry, I don't understand. By "regression that we use to gate
> > changes" do you mean that the automated testing you're orchestrating
> > does "regression-everything"?
> >
> > -- Matt
> > > Date: Mon, 25 Jan 2016 14:46:18 -0800
> > > From: "David L. Rager" <notifications@github.com>
> > > Reply-To: acl2/acl2 <reply@reply.github.com>
> > > Cc: MattKaufmann <kaufmann@cs.utexas.edu>
> > >
> > >
> > > [1:text/plain Hide]
> > >
> > > Well, that's simpler, but it still means the regression that we use to
> > gate changes is slow. I happen to be caring about that time today, so
> I've
> > made a note. Note that others may feel free to disregard my note.
> > >
> > > ---
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/acl2/acl2/issues/580#issuecomment-174707937
> >
> > >
> > > [2:text/html Show]
> > >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/acl2/acl2/issues/580#issuecomment-174738841>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acl2/acl2/issues/580#issuecomment-174743104>.
>



-- 
Jared C. Davis <jared@cs.utexas.edu>
11410 Windermere Meadows
Austin, TX 78759
http://www.cs.utexas.edu/users/jared/

**Comment by ragerdl** [comment]
Fixed in:

https://github.com/acl2/acl2/commit/16d4fb0f768a9284474756ce48f7cabc524e290a

Thanks Jared!

**Comment by russinoff** [comment]
Yes, thanks Jared.  (Sorry, I've been sick and out of the loop.)
