### ISSUE TITLE
Books thwart an attempt to strengthen defun redundancy

### ISSUE THREAD

**Issue by MattKaufmann** [acl2/acl2#582]
This Issue summarizes a minor ACL2 annoyance that could be fixed if
someone wants to mess with the books.  I'd consider doing it, but
although this might be a quick and easy task, it could also become
tedious and unwieldy, so I don't want to start it.  I figured I'd lay
out the issue here, in case someone is inspired to try.

Stop reading here if you have better things to do!

.....

I noticed that one can get an error trying to certify the following
book.  The problem is that the second definition of foo is redundant
on the first pass of certify-book, so bar goes through on the first
pass; but on the second pass, bar fails because foo is not
guard-verified.

```
(in-package "ACL2")

(local
 (defun foo (x)
   (declare (xargs :guard t :verify-guards t))
   x))

(defun foo (x)
  (declare (xargs :guard t :verify-guards nil))
  x)

(defun bar (x)
  (declare (xargs :guard t))
  (foo x))
```

There's nothing really wrong with this that I know of, but this sort
of behavior could be annoying to someone developing a book: events are
all admitted, but then certification fails.  At some level this is
just an instance of the failure of local incompatibility checking, but
yuck; seems like a nice thing to fix.

I've written a patch, but I got a lot of regression failures.  Many of
them that I looked at were due to the definitions of list-fix in the
following two books.  Both define list-fix the same way, first with
:verify-guards nil and then with a verify-guards event.

```
/Users/kaufmann/acl2/acl2-git-scratch/books/std/lists/list-fix.lisp
/Users/kaufmann/acl2/acl2-git-scratch/books/std/lists/list-defuns.lisp
```

So when both are included, say list-fix.lisp and then list-defuns.lisp
the new stronger redundancy check fails because of the following
sequence of events.

```
; list-fix.lisp
(defun list-fix (...) (... :verify-guards nil ...) ...)
(verify-guards list-fix)
; list-defuns.lisp
(defun list-fix (...) (... :verify-guards nil ...) ...) ; no longer redundant!
(verify-guards list-fix)
```

There are other examples of this phenomenon.  For example
the function union-lsts is defined identically in the following two
books, but the first defines it after (set-verify-guards-eagerness 2)
while the second defines it after (set-verify-guards-eagerness 0).

```
~/acl2/acl2-git-scratch/books/acl2s/cgen/utilities.lisp
~/acl2/acl2-git-scratch/books/acl2s/cgen/simple-graph-array.lisp
```

Unfortunately, the second includes the first, so again we have an
error.

If I knew that these were the only two such problems, I'd fix them
myself.  But quite possibly there are many others.

I've attached the patch.  To try this out, just search for

```
(defun redundant-or-reclassifying-defunp0
```

in ACL2 source file defuns.lisp, and replace that defun by the one in
the attached file.  (First make sure that the only changes to that
defun are in the region between the comments "PATCH STARTS HERE" and
"PATCH ENDS HERE"; that is indeed the case today, but who knows, that
function might change in the future.)

If you fix the books so that the command

```
time nice make -j 8 regression-everything USE_QUICKLISP=1
```

passes with glucose installed, let me know and I'll install the patch.
[defun-verify-guards-redundancy.lisp.txt](https://github.com/acl2/acl2/files/108292/defun-verify-guards-redundancy.lisp.txt)

**Comment by kini** [comment]
How would you propose to fix these failures, actually?

Take the list-fix function, for example.  Viewed alone, there's nothing really wrong with each of the two definitions. We could contrive to make these functions be guard-verified immediately during the admission of the defun, which I guess would solve the problem.

However, wouldn't that mean that, as a rule, we should never admit functions and guard-verify them later, for fear of someone eventually copying and pasting our defun and verify-guards forms into another book and then trying to include both books in a third?  That seems a bit extreme, no...?

**Comment by MattKaufmann** [comment]
Sorry, I posted this along time ago and it would take substantial effort
to get my head around it to be able to answer your question.  So I'll
pass for now; but if this becomes an important issue for you or anyone,
then of course that's a different situation.

**Comment by airbornemihir** [comment]
I think recent changes to `list-fix` and other functions have made this patch applicable. I tried it last night and everything seems to work on top of a recent version of the ACL2+books distribution; I can share more details if needed.

**Comment by MattKaufmann** [comment]
OK, I've reviewed this issue and I think I understand.

By the way, an earlier comment from @kini makes a reasonable point.  But it's often not great practice to cut-and-paste like that; better might be to move the definition in question into a separate book, to be included in the other two books.

So if the regression-everything passes then I think this is probably a good change.  I think it might be best if I just go ahead and make the change, after I test it myself with regression-everything, and revert it if it causes problems for existing books (outside the community books).

**Comment by MattKaufmann** [comment]
@airbornemihir I couldn't even build ACL2 with that patch.  I started making changes to try to do the build, but then I realized that it's hard for me to imagine that you ran a successful regression using the patch, given that the executable doesn't even build.  I've attached my patch here.
[defuns-downgrade-to-ideal.lisp.txt](https://github.com/acl2/acl2/files/4995713/defuns-downgrade-to-ideal.lisp.txt)

**Comment by solswords** [comment]
I'm not sure this is something that should be fixed.  The following comment (below the change, in the same function) is about verify-termination rather than verify-guards, but wouldn't there be an analogous problem?
```
; It's important to allow such to be redundant in order to avoid the following
; problem, pointed out by Jared Davis.  Imagine that one book defines a
; function in :logic mode, while another has an identical definition in
; :program mode followed by verify-termination.  Also imagine that both books
; are independently certified.  Now imagine, in a fresh session, including the
; first book and then the second.  Inclusion of the second causes an error in
; Version_3.4 because of the "downgrade" from :logic mode to :program mode at
; the time the :program mode definition is encountered.
```

**Comment by airbornemihir** [comment]
Oops, it looks like a previous comment of mine didn't go through. My earlier report that this patch works was erroneous - I ran a different make command than my usual one, I think (I have a somewhat complicated make command that builds the whole regression suite but reduces the time taken for the filesystem books) and somehow skipped over rebuilding the ACL2 executable. For what it's worth I don't see this as a pressing issue in need of fixing, either.

**Comment by MattKaufmann** [comment]
I think you're right, @solswords; thanks for pointing that out.  OK, I'm going to close this issue; I don't think it's worthwhile spending any more time on it.  Sorry about raising it in the first place.
