### ISSUE TITLE
vl shell does not work?

### ISSUE THREAD

**Issue by pennyan** [acl2/acl2#583]
Hi, about VL kit, when running vl shell I got "Raw lisp definition not installed?". I saw in the code that vl shell will always print that sentence. Does that mean it is not supposed to be working now?

**Comment by ragerdl** [comment]
Hi Yan,

You're probably looking at the version that exists in raw Lisp only when
the "real" version hasn't been loaded yet.  There should be some way to
load the "real" version... more later, but let us know if you figure it out.

Best,
David

**Comment by jaredcdavis** [comment]
Hi,

Sorry, I screwed this up a few days ago.  I have a fix but haven't pushed
it yet.  Will do so tomorrow.

Cheers,
Jared

On Thu, Jan 28, 2016 at 7:09 PM, David L. Rager <notifications@github.com>
wrote:

> Hi Yan,
>
> You're probably looking at the version that exists in raw Lisp only when
> the "real" version hasn't been loaded yet. There should be some way to
> load the "real" version... more later, but let us know if you figure it
> out.
>
> Best,
> David
>
> On Thu, Jan 28, 2016 at 5:45 PM, pennyan <notifications@github.com> wrote:
>
> > Hi, about VL kit, when running vl shell I got "Raw lisp definition not
> > installed?" I saw in the code that vl shell will always print that
> sentence
> > Does that mean it is not supposed to be working now?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/acl2/acl2/issues/583>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/acl2/acl2/issues/583#issuecomment-176507282>.
>



-- 
Jared C. Davis <jared@cs.utexas.edu>
11410 Windermere Meadows
Austin, TX 78759
http://www.cs.utexas.edu/users/jared/

**Comment by jaredcdavis** [comment]
Fixed in 34443b07b9d3b2ab7bfd78d46b0de7cac33068ba
