### ISSUE TITLE
Use with-output to cut down on macro printing

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#59]
_From [rage...@gmail.com](https://code.google.com/u/102895947197065323718/) on April 24, 2013 15:47:24_

When an event fails in cutil::defaggregate, it typically takes a moderately tricky use of :trans1, copy+pasting, redo-flat, or set-ld-pre-eval-print to debug a failure.  Here are some things that would make it easier to debug uses of cutil:

(1) Print less of the output associated with the make-events that surround the failed event

(2) Provide a form (or pair of forms) that enable the user to replay an attempt that only includes the failed event.

_Original issue: http://code.google.com/p/acl2-books/issues/detail?id=58_

**Comment by jaredcdavis** [comment]
I think this is pretty much solved by now so I'm going to close it.  If some particular macro still has a problem, we can open a new issue and deal with it.
