### ISSUE TITLE
Cleanup smtlink missing message

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#612]
Someone notes, "When I do a "make clean-books" in the ACL2 directory, which is
really a "make moreclean" in the books/ directory, I get this line in the output:"

```
Determining whether Smtlink is supported -- BOZO todo, for now pretending it does not!
```

Can you clean that up?

**Comment by ragerdl** [comment]
I've pushed a change into the testing branch that cleans up the message.

That being said, it'd be good to call the actual smt solver instead of just `smtlink`.  @pennyan , if you can provide me (1) the name of the executable and (2) what you do to get the version information out of it, I'll make that change.

**Comment by pennyan** [comment]
Ummm, does github remind me if somebody @ed me? Sorry I saw this late. Do you still need my help @ragerdl ? I don't quite understand what you mean by "it'd be good to call the actual smt solver instead of just smtlink" and why you need these (1) and (2) information. Could you clarify? :)

**Comment by ragerdl** [comment]
For some reason, I'm imagining that we had an offline conversation about this.  If y'all are happy with the way SMT Link is running, then I don't think there's anything to do.  I'll close this issue, because it's about the message, and I cleaned that up :).
