### ISSUE TITLE
cert.pl is not treating absolute path correctly

### ISSUE THREAD

**Issue by pennyan** [acl2/acl2#653]
Reading the :doc Pathname, I get the understanding that absolute pathnames are supported by include-books and the only thing one has to do is:

`(include-book "/the-absolute-path-name")`

However cert.pl doesn't seem to be consistent with it. It seems to think of absolute names as relative names and tries to append the current directory onto the beginning of the absolute name.

One can demonstrate this by generating a file that contains:

`(in-package "ACL2")`
`(include-book "/absolute-path-to-any-acl2-book")`

And then run cert.pl on that file.

I demonstrated this with the cert.pl for git commit hash:
19c8e87eb12a4845475ae352a7b936eb58241b70

**Comment by ragerdl** [comment]
I wasn't able to replicate this, but it looks like Sol was and that he has submitted a fix (probably to testing).

**Comment by solswords** [comment]
I think this is fixed; @pennyan feel free to reopen if it isn't solved for you.
