### ISSUE TITLE
Nonstd build failing in projects/sat/proof-checker-array

### ISSUE THREAD

**Issue by solswords** [acl2/acl2#674]
Probably this should just be fixed by putting
;; cert-param: (non-acl2r)
in any books that need them, but optionally someone could try to make them compatible with acl2(r).

I can't seem to assign this to @nwetzler (anyone know why?) but anyone with a little time to build acl2(r) and the relevant books could probably fix this.

**Comment by ragerdl** [comment]
I've invited nwetzler to the team, but he has to accept the invite before we can tag him.

**Comment by nwetzler** [comment]
Thanks for fixing this, Matt.  It looks like it's because I used "rationalp" where you need "real/rationalp" for ACL2r.  Should I try building any future commits with ACL2r before merging?

**Comment by MattKaufmann** [comment]
Hi, Nathan --

Right -- it was an easy fix (just a couple such changes).  My (strong)
opinion is that it's too much of a burden to run with ACL2(r) before
checking in -- I virtually never do so, anyhow, unless it's for a
release.

-- Matt
