### ISSUE TITLE
Kestrel SOFT: cant define instance of exists quantifier

### ISSUE THREAD

**Issue by nadezhin** [acl2/acl2#690]
The code below gives an error `:rewrite argument for a defun-sk form that uses the exists quantifier`.

``` lisp
(include-book "kestrel/soft/top" :dir :system)

(defunvar ?p (*) => *)

(defun-sk2 exists[?p] (?p) ()
  (exists x (?p x)))
(verify-guards exists[?p])

(defun-inst exists[symbolp]
  (exists[?p] (?p . symbolp)))
```

**Comment by acoglio** [comment]
Thank you for the clear bug report. I have a fix ready but I'm waiting for the testing branch to be unbroken before I can push my fix.

Please feel free to assign me any issue pertaining to the Kestrel Books (the assignment should send me an email notification). Also, please let me know if you have any question or comment on SOFT or the utilities in the other Kestrel Books.

**Comment by acoglio** [comment]
The bug is fixed in https://github.com/acl2/acl2/commit/b7c7960cb11c82d73f45b9dca7ead4b213b8ea00
