### ISSUE TITLE
Broken build

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#691]
Hi,

The build seems to be broken right now.  I suspect this commit, so I'm assigning it to @solswords.  

https://github.com/acl2/acl2/commit/5be64a5e74616aefaf52c4897a0a3a39a4720b32

I'll go ahead and clean and restart the build, but I'll be a bit surprised if that fixes this particular error.

David

**CERTIFICATION FAILED** for /var/lib/jenkins/jobs/acl2-testing/workspace/books/projects/legacy-defrstobj/groundwork/demo5.lisp

   |         (:REWRITE NTH-0-CONS)
   |         (:TYPE-PRESCRIPTION STP))
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | Prover steps counted:  89
   | STP-OF-CREATE-ST
   | 
   | Summary
   | Form:  ( DEFUN WEAK-STP ...)
   | Rules: NIL
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | WEAK-STP
   | 
   | Summary
   | Form:  ( DEFUN NON-EXECUTABLE-NTH ...)
   | Rules: NIL
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | NON-EXECUTABLE-NTH
   | 
   | Summary
   | Form:  ( IN-THEORY (ENABLE ...))
   | Rules: NIL
   | Time:  0.00 seconds (prove: 0.00, print: 0.00, other: 0.00)
   | (:NUMBER-OF-ENABLED-RUNES 1954)
   | Subgoal 2
   | Subgoal 2'
   | Subgoal 1
   | Subgoal 1.3
   | Subgoal 1.3'
   | Subgoal 1.3''
   | Subgoal 1.3'''
   | Subgoal 1.2
   | Subgoal 1.2'
   | Subgoal 1.2''
   | Subgoal 1.2'''
   | Subgoal 1.1
   | Subgoal *2/8
   | Subgoal *2/7
   | Subgoal *2/7'
   | Subgoal *2/7''
   | Subgoal *2/7'''
   | Subgoal *2/7'4'
   | Subgoal *2/7'5'
   | Subgoal *2/7'6'
   | Subgoal *2/6
   | Subgoal *2/6'
   | Subgoal *2/6''
   | Subgoal *2/6'''
   | Subgoal *2/6'4'
   | Subgoal *2/6'5'
   | Subgoal *2/6'6'
   | Subgoal *2/5
   | Subgoal *2/5'
   | Subgoal *2/5''
   | Subgoal *2/5'''
   | Subgoal *2/5'4'
   | Subgoal *2/5'5'
   | Subgoal *2/5'6'
   | Subgoal *2/4
   | Subgoal *2/4'
   | Subgoal *2/4''
   | Subgoal *2/4'''
   | Subgoal *2/4'4'
   | Subgoal *2/4'5'
   | Subgoal *2/4'6'
   | Subgoal *2/4'7'
   | Subgoal *2/3
   | Subgoal *2/3'
   | Subgoal *2/3''
   | Subgoal *2/3'''
   | Subgoal *2/3'4'
   | Subgoal *2/3'5'
   | Subgoal *2/3'6'
   | Subgoal *2/2
   | Subgoal *2/2'
   | Subgoal *2/2''
   | Subgoal *2/2'''
   | Subgoal *2/2'4'
   | Subgoal *2/2'5'
   | Subgoal *2/2'6'
   | Subgoal *2/2'7'
   | Subgoal *2/1
   | Subgoal *2.6/3
   | Subgoal *2.6/2
   | Subgoal *2.6/2'
   | Subgoal *2.6/2''
   | Subgoal *2.6/2'''
   | Subgoal *2.6/2'4'
   | Subgoal *2.6/2'5'
   | Subgoal *2.6/2'6'
   | Subgoal *2.6/1
   | Subgoal *2.6.1/3
   | Subgoal *2.6.1/2
   | Subgoal *2.6.1/2'
   | Subgoal *2.6.1/2''
   | Subgoal *2.6.1/2'''
   | Subgoal *2.6.1/1
   | Subgoal *2.6.1.1/4
   | Subgoal *2.6.1.1/3
   | Subgoal *2.6.1.1/3'
   | Subgoal *2.6.1.1/3''
   | Subgoal *2.6.1.1/3'''
   | Subgoal *2.6.1.1/2
   | Subgoal *2.6.1.1/1
   | Subgoal *2.6.1.1/1'
   | Subgoal *2.6.1.1/1''
   | Subgoal *2.6.1.1/1'''
   | Subgoal *2.6.1.1.1/4
   | Subgoal *2.6.1.1.1/3
   | Subgoal *2.6.1.1.1/3'
   | Subgoal *2.6.1.1.1/3''
   | Subgoal *2.6.1.1.1/3'''
   | Subgoal *2.6.1.1.1/2
   | Subgoal *2.6.1.1.1/1
   | Subgoal *2.6.1.1.1/1'
   | Subgoal *2.6.1.1.1/1''
   | Subgoal *2.6.1.1.1/1'''
   | Subgoal *2.6.1.1.1.1/4
   | Subgoal *2.6.1.1.1.1/3
   | Subgoal *2.6.1.1.1.1/3'
   | Subgoal *2.6.1.1.1.1/3''
   | Subgoal *2.6.1.1.1.1/3'''
   | Subgoal *2.6.1.1.1.1/3'4'
   | Subgoal *2.6.1.1.1.1/3'5'
   | Subgoal *2.6.1.1.1.1/2
   | Subgoal *2.6.1.1.1.1/1
   | Subgoal *2.6.1.1.1.1/1'
   | Subgoal *2.6.1.1.1.1/1''
   | Subgoal *2.6.1.1.1.1/1'''
   | Subgoal *2.6.1.1.1.1/1'4'
   | Subgoal *2.6.1.1.1.1/1'5'
   | Subgoal *2.6.1.1.1.1.1/3
   | Subgoal *2.6.1.1.1.1.1/3'
   | Subgoal *2.6.1.1.1.1.1/3''
   | Subgoal *2.6.1.1.1.1.1/2
   | Subgoal *2.6.1.1.1.1.1/1
   | Subgoal *2.6.1.1.1.1.1/1'
   | Subgoal *2.6.1.1.1.1.1/1''
   | Subgoal *2.6.1.1.1.1.1/1'''
   | Subgoal *2.6.1.1.1.1.1/1'4'
   | 
   | 
   | ACL2 Error in ( DEFUN GOOD-STP ...):  The proof of the guard conjecture
   | for GOOD-STP has failed.  You may wish to avoid specifying a guard,
   | or to supply option :VERIFY-GUARDS NIL with the :GUARD.  Otherwise,
   | you may wish to specify :GUARD-DEBUG T; see :DOC verify-guards.
   | 
   | 
   | 
   | Summary
   | Form:  ( DEFUN GOOD-STP ...)
   | Rules: ((:COMPOUND-RECOGNIZER TRUE-LISTP-WHEN-ST-FOOP)
   |         (:DEFINITION HIDE)
   |         (:DEFINITION INTEGER-ARRAY-REC-PAIR-P)
   |         (:DEFINITION LEN)
   |         (:DEFINITION LENGTH)
   |         (:DEFINITION NON-EXECUTABLE-NTH)
   |         (:DEFINITION NOT)
   |         (:DEFINITION ST-FOO-BAD)
   |         (:DEFINITION ST-FOO-LENGTH)
   |         (:DEFINITION ST-FOOP)
   |         (:DEFINITION ST-GOOD)
   |         (:DEFINITION STP)
   |         (:DEFINITION SYNP)
   |         (:DEFINITION TRUE-LISTP)
   |         (:DEFINITION WEAK-STP)
   |         (:ELIM CAR-CDR-ELIM)
   |         (:EXECUTABLE-COUNTERPART ACL2-NUMBERP)
   |         (:EXECUTABLE-COUNTERPART BINARY-+)
   |         (:EXECUTABLE-COUNTERPART CONSP)
   |         (:EXECUTABLE-COUNTERPART EQUAL)
   |         (:EXECUTABLE-COUNTERPART INTEGER-TR-DELETE-INDICES)
   |         (:EXECUTABLE-COUNTERPART NOT)
   |         (:EXECUTABLE-COUNTERPART NTH)
   |         (:EXECUTABLE-COUNTERPART TAU-SYSTEM)
   |         (:EXECUTABLE-COUNTERPART UNARY--)
   |         (:FAKE-RUNE-FOR-TYPE-SET NIL)
   |         (:INDUCTION LEN)
   |         (:INDUCTION ST-FOOP)
   |         (:INDUCTION TRUE-LISTP)
   |         (:REWRITE INTEGER-LISTP-WHEN-ST-FOOP)
   |         (:REWRITE NTH-0-CONS)
   |         (:REWRITE NTH-ADD1)
   |         (:REWRITE SIMPLIFY-EQUAL-PLUS-CONSTANTS)
   |         (:TYPE-PRESCRIPTION LEN))
   | Time:  0.30 seconds (prove: 0.29, print: 0.01, other: 0.00)
   | Prover steps counted:  22634
   | 
   | ---
   | The key checkpoint goals, below, may help you to debug this failure.
   | See :DOC failure and see :DOC set-checkpoint-summary-limit.
   | ---
   | 
   | *** Key checkpoints at the top level: ***
   | 
   | Subgoal 1.3
   | (IMPLIES (AND (TRUE-LISTP ST)
   |               (EQUAL (LEN ST) 6)
   |               (ST-FOOP (NTH *ST-FOOI* ST))
   |               (EQUAL (LEN (NTH *ST-FOOI* ST)) 32)
   |               (NTH *ST-GOOD* ST)
   |               (EQUAL (NTH *ST-FOO-BAD* ST)
   |                      (INTEGER-TR-DELETE-INDICES 32 (NTH *ST-FOO-BAD* ST)))
   |               (NTH *ST-FOO-BAD* ST))
   |          (EQUAL (NTH *ST-FOO-BAD* ST)
   |                 (INTEGER-TR-DELETE-INDICES 31 (NTH *ST-FOO-BAD* ST))))
   | 
   | Subgoal 1.2
   | (IMPLIES
   |      (AND (TRUE-LISTP ST)
   |           (EQUAL (LEN ST) 6)
   |           (ST-FOOP (NTH *ST-FOOI* ST))
   |           (EQUAL (LEN (NTH *ST-FOOI* ST)) 32)
   |           (NTH *ST-GOOD* ST)
   |           (NOT (EQUAL (NTH *ST-FOO-BAD* ST)
   |                       (INTEGER-TR-DELETE-INDICES 32 (NTH *ST-FOO-BAD* ST)))))
   |      (NOT (EQUAL (NTH *ST-FOO-BAD* ST)
   |                  (INTEGER-TR-DELETE-INDICES 31 (NTH *ST-FOO-BAD* ST)))))
   | 
   | *** Key checkpoints under a top-level induction: ***
   | 
   | Subgoal *2/7'
   | (IMPLIES
   |      (AND (CONSP ST)
   |           (NOT (EQUAL (NTH 1 (CDR ST))
   |                       (INTEGER-TR-DELETE-INDICES 31 (NTH 1 (CDR ST)))))
   |           (TRUE-LISTP (CDR ST))
   |           (EQUAL (FIX (LEN (CDR ST))) 5)
   |           (ST-FOOP (NTH *ST-FOOI* ST))
   |           (EQUAL (LEN (NTH *ST-FOOI* ST)) 32)
   |           (NTH *ST-GOOD* ST)
   |           (NOT (EQUAL (NTH *ST-FOO-BAD* ST)
   |                       (INTEGER-TR-DELETE-INDICES 32 (NTH *ST-FOO-BAD* ST)))))
   |      (NOT (EQUAL (NTH *ST-FOO-BAD* ST)
   |                  (INTEGER-TR-DELETE-INDICES 31 (NTH *ST-FOO-BAD* ST)))))
   | 
   | Subgoal *2/6'
   | (IMPLIES
   |      (AND (CONSP ST)
   |           (EQUAL (NTH 1 (CDR ST))
   |                  (INTEGER-TR-DELETE-INDICES 32 (NTH 1 (CDR ST))))
   |           (TRUE-LISTP (CDR ST))
   |           (EQUAL (FIX (LEN (CDR ST))) 5)
   |           (ST-FOOP (NTH *ST-FOOI* ST))
   |           (EQUAL (LEN (NTH *ST-FOOI* ST)) 32)
   |           (NTH *ST-GOOD* ST)
   |           (NOT (EQUAL (NTH *ST-FOO-BAD* ST)
   |                       (INTEGER-TR-DELETE-INDICES 32 (NTH *ST-FOO-BAD* ST)))))
   |      (NOT (EQUAL (NTH *ST-FOO-BAD* ST)
   |                  (INTEGER-TR-DELETE-INDICES 31 (NTH *ST-FOO-BAD* ST)))))
   | 
   | Subgoal *2/5'
   | (IMPLIES
   |      (AND (CONSP ST)
   |           (NOT (NTH 4 (CDR ST)))
   |           (TRUE-LISTP (CDR ST))
   |           (EQUAL (FIX (LEN (CDR ST))) 5)
   |           (ST-FOOP (NTH *ST-FOOI* ST))
   |           (EQUAL (LEN (NTH *ST-FOOI* ST)) 32)
   |           (NTH *ST-GOOD* ST)
   |           (NOT (EQUAL (NTH *ST-FOO-BAD* ST)
   |                       (INTEGER-TR-DELETE-INDICES 32 (NTH *ST-FOO-BAD* ST)))))
   |      (NOT (EQUAL (NTH *ST-FOO-BAD* ST)
   |                  (INTEGER-TR-DELETE-INDICES 31 (NTH *ST-FOO-BAD* ST)))))
   | 
   | Note: There are three additional key checkpoints under a top-level
   | induction.  See :DOC set-checkpoint-summary-limit to change the number
   | printed.
   | 
   | ACL2 Error in ( DEFUN GOOD-STP ...):  The proof of the guard conjecture
   | for GOOD-STP has failed; see the discussion above about :VERIFY-GUARDS
   | and :GUARD-DEBUG.  See :DOC failure.
   | 
   | ******** FAILED ********
   | 
   | Summary
   | Form:  ( ENCAPSULATE NIL (LOCAL ...) ...)
   | Rules: NIL
   | Time:  0.31 seconds (prove: 0.29, print: 0.01, other: 0.01)
   | Prover steps counted:  22634
   | 
   | ACL2 Error in ( ENCAPSULATE NIL (LOCAL ...) ...):  See :DOC failure.
   | 
   | ******** FAILED ********
   | 
   | Summary
   | Form:  (CERTIFY-BOOK "demo5" ...)
   | Rules: NIL
   | Warnings:  Ttags
   | Time:  5.80 seconds (prove: 0.40, print: 0.03, other: 5.38)
   | Prover steps counted:  45407
   | 
   | ACL2 Error in (CERTIFY-BOOK "demo5" ...):  See :DOC failure.
   | 
   | ******** FAILED ********
   | ; (EV-REC *RETURN-LAST-ARG3* ...) took 
   | ; 5.80 seconds realtime, 5.77 seconds runtime
   | ; (324,847,968 bytes allocated).
   | ACL2 !>Bye.
   | Exit code from ACL2 is 0
   | demo5.cert seems to be missing

**CERTIFICATION FAILED** for /var/lib/jenkins/jobs/acl2-testing/workspace/books/projects/legacy-defrstobj/groundwork/demo5.lisp

**Comment by solswords** [comment]
Yes, my fault -- sorry about that. Fix incoming.
