### ISSUE TITLE
ACL2 make fails due to dependency on rendered-doc.lsp

### ISSUE THREAD

**Issue by solswords** [acl2/acl2#692]
Making ACL2 on a fresh clone of this git repository is failing for me because it's trying to make rendered-doc.lsp before the ACL2 executable exists.  It looks like that's due to commit 7c31d961c, " Arranged for `make' to be a no-op when no supporting files have changed": 
full: acl2-status.txt
acl2-status.txt: TAGS $(ACL2_DEPS)
ACL2_DEPS includes doc.lisp
doc.lisp: ... books/system/doc/rendered-doc.lsp
books/system/rendered-doc.lsp uses ACL2 to build itself (though it doesn't depend on ACL2).

$(PREFIXsaved_acl2) and TAGS also depend on doc.lisp.

The attached version removes the doc.lisp dependencies of $(PREFIXsaved_acl2) and acl2-status.txt and makes acl2-status.txt depend on acl2r but not TAGS (following the warning in the comment above it).  It also adds a dependency from rendered-doc.lsp to $(PREFIXsaved_acl2) because it seems like that should be there.  It seems to work, but I'm a little out of my depth -- maybe there's a good reason for acl2-status.txt to depend on TAGS, for example.  

[GNUmakefile.txt](https://github.com/acl2/acl2/files/751024/GNUmakefile.txt)

**Comment by MattKaufmann** [comment]
What's the protocol -- should I close this issue or should the closer be the one who created the issue?

**Comment by kini** [comment]
I don't know about ACL2-specific protocol, but on github generally it's usual for the maintainer (i.e. you) to close the bug when they believe it has been addressed.
