### ISSUE TITLE
cert.pl can't handle large dependencies

### ISSUE THREAD

**Issue by pennyan** [acl2/acl2#694]
cert.pl will fail with this error if one target has a huge number of dependencies:
`make[1]: execvp: /bin/bash: Argument list too long`

Tracing through the perl scripts, it seems to me that, it is this file and this line:
https://github.com/acl2/acl2/blob/master/books/build/make_cert#L109
that generates a bash command with all dependencies creating this error.

It seems that cert.pl will generate a Makefile-tmp with all dependencies. This
Makefile-tmp include `$(ACL2_SYSTEM_BOOKS)/build/make_cert` which 
will generate a bash command using make_cert_help.pl and put in place all
dependencies. If one dependency becomes huge, making the argument to
a system call exceeds MAX_ARG_STRLEN, then an error like this will be 
triggered. In my case, I've got 6000 included books each with around 23 
characters in their names.

My problem came up because I was trying to parallel a huge amount of book 
certification. The books are independent therefore is very easy to go parallel.
In the end I want to merge the results from all these independent books and
that's where the dependency becomes huge. 

I can make the names shorter or the number of paralleling smaller to temporarily
solve the problem@@ but let me know if you want to fix this problem or if cert.pl
actually provides a way around it.

**Comment by solswords** [comment]
It looks like the prerequisites passed in to make_cert_help.pl on the command line aren't actually used.  (It assigns "my $PREREQS = \@ARGV" after shifting off a few things, but then never uses PREREQS.)  So I think you could do the following without hurting anything:
 - delete the "$^" arguments from make_cert
 - delete the assignment of PREREQS in make_cert_help.pl
Could you try that and see if it works?

**Comment by pennyan** [comment]
Hi, I tried your suggestion with my example and it works! Should I create a pull request for fixing it? The version of ACL2 I tried with is: git commit hash: a2884f5aa1cc62ae1e0f0161208ad94f60824737, it seems that the commits after are independent of this fix.

**Comment by kini** [comment]
FYI the underlying problem is a bug, or perhaps missing feature, in GNU make, which is addressed by a patch here: https://savannah.gnu.org/bugs/index.php?45763

(for future reference, if anyone runs into this problem somewhere where simply removing command line arguments from the make recipe isn't a workable solution)

**Comment by solswords** [comment]
Yes, @pennyan that would be great, thanks.
Recent versions of GNU make have several possible fixes -- I wasn't aware of the one kini mentioned, but at least non-shell-dependent file i/o exists in maybe 3.90 or thereabouts -- but some of us are stuck on 3.81 (released 2006) for some reason.

**Comment by kini** [comment]
Yeah, we're using 3.81 as well :/ The fix I mentioned isn't even in a recent version of GNU make, it's just a patch on their bug tracker for now. Debian has been applying this patch for a few years now, so on newish Debian systems you might not see this problem.
