### ISSUE TITLE
Add a fixing function for vl::string-list-listp

### ISSUE THREAD

**Issue by pennyan** [acl2/acl2#699]
Hi, this is more like a question-like friendly wishing. I wonder why even though centaur/vl/util/defs.lisp defines the deflist string-list-listp, but didn't give a fixing function for it. Is there a reason for it? I thought fxing functions are supposed to go with their types. I tried to use this type and needed a fixing function. Maybe you want me to define in my own package? Thanks!

**Comment by solswords** [comment]
That's a std::deflist, which doesn't make a fixing function itself.  If you
want, you could try changing it to an fty::deflist, which would.  If
everything still builds, then that's a perfectly fine change.

- Sol

**Comment by pennyan** [comment]
Ohoh, I seeeee. I will try that out.

**Comment by acoglio** [comment]
I'm not sure if this Issue is still relevant, but `fty::deflist` also provides the `:elementp-of-nil` option (maybe it was added after this Issue was opened?).

**Comment by pennyan** [comment]
Hi @acoglio, I think you are right. Should we try @solswords's suggestion or should I just close the issue?

**Comment by acoglio** [comment]
Hi @pennyan, I think that, if you are still using this VL library, it would be good to try Sol's suggestion so that you don't have to define the fixer in your own development, given that, as you note, it more naturally goes with the type.

**Comment by pennyan** [comment]
Hi @acoglio, I don't need this change anymore. I will close this issue then.
