### ISSUE TITLE
books/misc/profiling broken on latest CCL?

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#744]
books/misc/profiling seems to be broken on the latest CCL.  Not sure if it matters to anyone, but thought I'd mention it in case someone wants to work ahead for the time that they update their CCL.

**Comment by ragerdl** [comment]
@MattKaufmann asked some excellent questions.  Answering them, now that I'm not running out the door.

1. Do you have a CCL version number for the failure?

Clozure Common Lisp Version 1.12-dev/v1.12-dev.0-26-g19f105c  (LinuxX8664)

Once you have a working CCL git clone, you can obtain that version by running `git checkout 19f105c`.  You probably need to rebuild the lisp-kernel and `(rebuild-ccl :full t)` twice too.  FWIW, I'm guessing that this will stay broken, even as CCL gets updated.  But, you never know.  The solution may be as "simple" as getting CCL to bundle a package that's currently missing (something that may occur between now and when someone gets around to this).

2. Can you send me a specific form that breaks?  For example, will I see the error if I just start up ACL2
and run (profile-acl2)?

Just trying to certify the book causes a problem.  An approximation of the error message is at the end.

3.   If you used git, then please send me download instructions or point me to them (they're not at https://ccl.clozure.com/download.html).

Sure, https://github.com/clozure/ccl.  As suggested on that page, I had to download the binaries appropriate for the 1.12 development tree and unexpand them.


```
ACL2 Version 7.4.  Level 1.  Cbd 
"/import/.../acl2/acl2b/books/misc/".
System books directory "/import/.../acl2/acl2b/books/".
Type :help for help.
Type (good-bye) to quit completely out of ACL2.

ACL2 !>
Exiting the ACL2 read-eval-print loop.  To re-enter, execute (LP).
? #<Package "ACL2">
? PROVE
? CERTIFY-BOOK-FN
? 
ACL2 Version 7.4.  Level 1.  Cbd 
"/import/.../acl2/acl2b/books/misc/".
System books directory "/import/.../acl2/acl2b/books/".
Type :help for help.
Type (good-bye) to quit completely out of ACL2.

ACL2 !><state>
ACL2 !> "ACL2"
ACL2 !> (:EXIT 1)
ACL2 !> (PROVE PROOF-TREE
        WARNING OBSERVATION EVENT HISTORY)
ACL2 !> T
ACL2 !>NIL
ACL2 !> T
ACL2 !> :CONTINUE
ACL2 !>
TTAG NOTE: Adding ttag :PROFILING from book /import/.../acl2/acl2b/books/misc/profiling.
:PROFILING

; Book under certification: "/import/.../acl2/acl2b/books/misc/profiling.lisp"
 (7F532FFFD070) : 0 (PRINT-CALL-HISTORY :CONTEXT NIL :PROCESS NIL :ORIGIN NIL :DETAILED-P NIL :COUNT 10000 :START-FRAME-NUMBER 0 :STREAM #<SYNONYM-STREAM to *TERMINAL-IO* #x3020038397FD> :PRINT-LEVEL 2 :PRINT-LENGTH 5 :PRINT-STRING-LENGTH :DEFAULT :SHOW-INTERNAL-FRAMES NIL :FORMAT :TRADITIONAL) 965
 (7F532FFFD208) : 1 (CALL-CHECK-REGS CCL:PRINT-CALL-HISTORY :DETAILED-P NIL :COUNT 10000) 229
 (7F532FFFD240) : 2 (CHEAP-EVAL (CCL:PRINT-CALL-HISTORY :DETAILED-P NIL :COUNT *CCL-PRINT-CALL-HISTORY-COUNT*)) 101
 (7F532FFFD278) : 3 (PRINT-CALL-HISTORY) 229
 (7F532FFFD288) : 4 (OUR-ABORT #<CCL::SIMPLE-FILE-ERROR #x302003A119CD> OUR-ABORT) 189
<snip>
 (7F532FFFEDB0) : 46 (FUNCALL #'#<(:INTERNAL (CCL:TOPLEVEL-FUNCTION (CCL::LISP-DEVELOPMENT-SYSTEM T)))>) 109
 (7F532FFFEDD0) : 47 (FUNCALL #'#<(:INTERNAL CCL::MAKE-MCL-LISTENER-PROCESS)>) 661
 (7F532FFFEE68) : 48 (RUN-PROCESS-INITIAL-FORM #<TTY-LISTENER listener(1) [Active] #x3020004653FD> (#<CCL:COMPILED-LEXICAL-CLOSURE # #x302003835E4F>)) 813
 (7F532FFFEEF0) : 49 (FUNCALL #'#<(:INTERNAL (CCL::%PROCESS-PRESET-INTERNAL (CCL:PROCESS)))> #<TTY-LISTENER listener(1) [Active] #x3020004653FD> (#<CCL:COMPILED-LEXICAL-CLOSURE # #x302003835E4F>)) 581
 (7F532FFFEF98) : 50 (FUNCALL #'#<(:INTERNAL CCL::THREAD-MAKE-STARTUP-FUNCTION)>) 277
***********************************************
************ ABORTING from raw Lisp ***********
********** (see :DOC raw-lisp-error) **********
Error:  File "/import/.../ccl-github/contrib/huebner/advice-profiler/package.lisp" does not exist.
NOTE: See above for backtrace.
***********************************************

The message above might explain the error.  If not, and
if you didn't cause an explicit interrupt (Control-C),
then the root cause may be call of a :program mode
function that has the wrong guard specified, or even no
guard specified (i.e., an implicit guard of t).
See :DOC raw-lisp-error and see :DOC guards.

To enable breaks into the debugger (also see :DOC acl2-customization):
(SET-DEBUGGER-ENABLE T)
ACL2 !>Bye.
Exit code from ACL2 is 0
profiling.cert seems to be missing

```

**Comment by MattKaufmann** [comment]
I have identified the problem and emailed a CCL developer about a missing directory in the CCL distribution (contrib/huebner/advice-profiler/, in fact all of contrib/).

For the record:

To get/build a github version, I proceeded as follows, based on
instructions at https://github.com/clozure/ccl:

    mkdir <fresh_directory>
    cd <fresh_directory>

    git clone https://github.com/Clozure/ccl.git
    # Find the version number:
    git log -n 1 --name-only

    # [NOTE: change "darwin" to "linux" below if you're on linux.]

    # Download ccl-1.12-dev.0-darwinx86-binaries.tar.bz2 from:
    # https://github.com/clozure/ccl

    mv ~/Downloads/ccl-1.12-dev.0-darwinx86-binaries.tar.bz2 <fresh_directory>

    cd ccl
    tar --strip-components 1 -xf ../ccl-1.12-dev.0-darwinx86-binaries.tar.bz2

    ./dx86cl64
    (rebuild-ccl :full t)
    (quit)

    ./dx86cl64
    (rebuild-ccl :full t)
    (quit)
