### ISSUE TITLE
 Should glucose be required to build the manual, as is currently the case?

### ISSUE THREAD

**Issue by ragerdl** [acl2/acl2#789]
Matt Kaufmann writes:

> This email asks the question: Should glucose be required to build the
> manual, as is currently the case?  Background/details follow below:
> 
> The manual's build requires that glucose is installed, but I don't
> think that this requirement is intended; in particular, in :doc
> books-certification the section "Building the manual" doesn't anything
> about requiring glucose.
> 
> Specifically, I got an error building the manual in my books/
> directory as follows, after removing my glucose installation:
> 
> (setenv USE_QUICKLISP 1 ; ./build/cert.pl --acl2 acl2c -j 8 doc/top.lisp) >& make-manual.log&
> 
> The log showed failures for the following.
> 
> books/centaur/sv/tutorial/boothpipe.lisp
> books/centaur/sv/tutorial/alu.lisp
> 
> I think that the documentation can't be trivially excised from these
> books, since (at the least) they use defsvtv both to generate code and
> to generate documentation.
> 
> The good news is that after I temporarily re-installed glucose and
> certified those two books, and then uninstalled glucose again, I was
> able to finish building the manual.  So those really are the only two
> books supporting the manual for which glucose is necessary.  I suspect
> that we can even build the manual simply by avoiding those two.
> 
> Do we need to start require glucose for manual builds?  That seems a
> bit unfortunate somehow, to have yet more software required for
> building the documentation (quicklisp is already required).  On the
> other hand, it would probably also be unfortunate to eliminate the two
> books above, and maybe there will be other such books in the future.
> 
> Thoughts?  For example, is it feasible and appropriate to move
> documentation out of the two problematic books?

**Comment by ragerdl** [comment]
Hi,

I too prefer to not require glucose build the manual.  However, given
the immediate choice between:

  (1) having the SVTV documentation in the manual by default and
requiring glucose and

  (2) not having the SVTV documentation in the manual and not requiring glucose

my inclination is towards (1).  And this comes from someone who's used
SVTV a lot in the past, already knows the documentation, and isn't
even currently using SVTVs.  SVTVs are just too useful for hardware
verification to omit from the default build.


In an "ideal" situation, we'd "improve" cert.pl so that it would build
one version of the manual if glucose is installed and another version
of the manual if it's not.  Sounds complicated.  If someone wants to
propose and execute such a plan, imho, we should be open to it.  But,
is it worth the trouble?

People can still build their own version of the manual without much
effort -- it just so happens that doc/top.lisp creates the manual that
requires glucose.  I guess an "easy" thing to do would be to create
doc/top-no-glucose-required-help.lisp (move most of doc/top.lisp to
that file), doc/top-no-glucose-required.lisp, and doc/top.lisp (which
would include doc/top-no-glucose-required-help.lisp, the two
aforementioned SVTV books, and then save the traditional manual).
Note -- this may significantly slow down the build, as including so
many books twice may be time-consuming.

But really, based on my small corner of the universe, I suspect we'd
be spending our time adding a feature and complexity that no one would
use.  It's potentially easier to install glucose than it would be to
understand how to build doc/top-no-glucose-required.lisp.

$0.02,
David

(PS -- since quicklisp was mentioned, I feel compelled to state that,
to my knowledge, the quicklisp requirement is transparent to the user
-- it's already bundled as part of the ACL2 git repo.  Thus, quicklisp
isn't really "yet more software to download and install")

**Comment by solswords** [comment]
I haven't looked at it yet, but I think it's probably feasible to remove the actual proofs from the documentation generation for the SV tutorial.  I think ideally we'd be able to build just the documentation for the manual, and the actual proofs (with glucose) for full regressions, but it'd be nice if we didn't need to duplicate the books to do that.  Maybe something like we do for std/strings/defs-program and the like: have a wrapper that does a two-pass certify where in the first pass it loads the tutorial books in "program mode" (or with proofs skipped), generating the relevant documentation, and then just leaves the documentation for the second pass.

I could maybe do this someday, but I'm happy if anyone else gets to it first (or comes up with a simpler solution).

- Sol

**Comment by MattKaufmann** [comment]
I suspect that we're all happy to have just one ACL2+books
manual, not one with glucose and one without.  Probably it
makes sense to require glucose for now: David points out the
importance of the two books supporting the manual that
require glucose, and Sol's approach could take more effort
than anyone wants to spend.  Some of us have discussed
modifying :doc github-commit-code-using-pull-requests to
mention the desirability of building the manual as part of
testing when there are documentation changes or additions.
I plan to make that modification if nobody objects soon, and
to add that glucose needs to be installed.  I also plan to
add a defpointer for a new topic, glucose, that points to
satlink::sat-solver-options.

**Comment by ragerdl** [comment]
That all sounds good to me.  That being said, it just occurred to me that maybe those books can be built using `GL`'s `BDD`s instead of calling `glucose`.  @solswords, how feasible do you think that would be?  We could then remove those books' dependencies upon `glucose`.

**Comment by solswords** [comment]
I'd rather have the tutorial use SAT, because it's more versatile and
easier to use than BDDs, and because I think it'd be nicer not to have to
talk about the choice of BDD variable ordering.  Also not sure whether all
the problems in the tutoral are feasible for BDDs (or feasible without
choosing a specific order).

**Comment by ragerdl** [comment]
Fairly sure that we resolved that it is okay for glucose to be required to build the manual.  Closing this issue for now.
