### ISSUE TITLE
system/doc/render-doc.lisp failed certification

### ISSUE THREAD

**Issue by pennyan** [acl2/acl2#827]
The book system/doc/render-doc.lisp in most recent commit fails the certification with message:

   | ACL2 Error in UNSOUND-EVAL:  The symbol *FCHECKSUM-OBJ-STACK-BOUND-INIT*
   | (in package "ACL2") has the syntax of a constant, but has not been
   | defined.
   |
   | ; xdoc error in NOTE-8-1: Error: failed to evaluate @(`...`): ("Failed
   | to evaluate NOTE-8-1; trans eval failed?
   | "Error: failed to evaluate @(`...`): (\"Failed to evaluate ~x0; trans eval failed? ~x1.\"
   |      (#\\0 . *FCHECKSUM-OBJ-STACK-BOUND-INIT*)
   |      (#\\1 . T))".
   | "
   |      (#\0 . *FCHECKSUM-OBJ-STACK-BOUND-INIT*)
   |      (#\1 . T))
   | Writing rendered-doc.lsp
   |
   |
   | HARD ACL2 ERROR in XDOC::SAVE-ACL2-ONLY-MANUAL:  at least one syntax
   | error was encountered by XDOC; search above for "xdoc error" (but the
   | same error may be reported more than once).
   |
   | ; (DEFCONSTS ...): 9.32 seconds, 1,719,270,704 bytes
   |

A suspected typo?

**Comment by ragerdl** [comment]
Hi,

Kind of confused -- leeroy shows the book as building.  

http://leeroy.defthm.com/job/acl2-master/ws/books/system/doc/render-doc.cert.out/*view*/

Maybe you need to rebuild the acl2 image?

~David~

**Comment by MattKaufmann** [comment]
Good idea, David.  I think that this constant was first defined in
ACL2 on Feb. 10 (commit a22f48fd4308655e211365e6dd60fcbafc90c927).

I too have successfully certified that book, so Yan, if you rebuild
the executable as David suggested, then I think that problem will
disappear.

-- Matt

**Comment by pennyan** [comment]
Thank you @ragerdl and @MattKaufmann. Sounds like this is something wrong with my setup, instead of ACL2's problem. I'm wondering what do you usually do to rebuild the acl2 image? I'm pretty sure I had rebuilt it by doing "make LISP=..." in the ACL2 directory. But somehow you suggested my rebuilt didn't work. Maybe one needs to first delete the previous image?

**Comment by kini** [comment]
Hmm. Did you rebuild it from a checkout of the latest master? And did you clean all the books after doing so?

**Comment by MattKaufmann** [comment]
Yan, I don't think it should be necessary to do more than you did: no deletion or clean should be necessary.  When you build the books, remember to provide cert.pl with "--acl2 <path_to_new_acl2>".  If you still get a failure, then you may send me an email and I'll request logs from you so that I can help you to debug this.

**Comment by pennyan** [comment]
Hi @MattKaufmann , thank you for offering to help. I've successfully built the books. What I did is first to remove the acl2 image, then I did "make moreclean" in books. I suspect it's the second one that has solved my problem? @kini , I did rebuild from the latest master, maybe cleaning the books does help sometimes?

**Comment by pennyan** [comment]
Well, since this problem is resolved. I will close the issue.
