### ISSUE TITLE
Build failure when etags is missing

### ISSUE THREAD

**Issue by krobelus** [acl2/acl2#955]
Running `make LISP=$(which sbcl)` on current master fails when `etags` is not executable.
The failure seems to occur at https://github.com/acl2/acl2/blob/master/acl2-init.lisp#L856. Three lines above, there is a check that looks like it is supposed to skip the execution of `etags` if it's not available, but that doesn't seem to be working.

**Comment by MattKaufmann** [comment]
Thank you very much for the bug report!  I have a fix, which I plan to push to github today or tomorrow.  Just FYI, I insert the fix below (replacing the definition of `make-tags` that was on lines 845-888.  Everything after the second line below is unchanged.  (The return value is still 1 for an error, but that shouldn't cause `make` to fail.)

    (defun make-tags ()
      (when (not (eql (ignore-errors (system-call "which" '("etags"))) 0))
        (format t "SKIPPING etags: No such program is in the path.")
        (return-from make-tags 1))
      (system-call "etags"
                   (let* ((fmt-str
                           #+(or cmu sbcl clisp ccl) "~a.lisp"
                           #-(or cmu sbcl clisp ccl) " ~a.lisp")
                          (lst (append '("acl2.lisp"
                                         "acl2-check.lisp"
                                         "acl2-fns.lisp"
                                         "init.lisp"
                                         "acl2-init.lisp"
                                         "akcl-acl2-trace.lisp"
                                         "allegro-acl2-trace.lisp"
                                         "openmcl-acl2-trace.lisp")
                                       (let ((result nil))
                                         (dolist
                                           (x *acl2-files*)

    ; Since we don't want to edit doc.lisp, don't go there with tags.

                                           (when (not (equal x "doc.lisp"))
                                             (setq result
                                                   (cons (format nil fmt-str x)
                                                         result))))
                                         (reverse result)))))

    ; We want to be sure to include the *-raw.lisp files even if we are not
    ; building the hons version, in order to assist in maintaining both versions.

                     (append lst (list "hons-raw.lisp"
                                       "memoize-raw.lisp"
                                       "multi-threading-raw.lisp"
                                       "futures-raw.lisp"
                                       "parallel-raw.lisp"
                                       "serialize-raw.lisp")))))

**Comment by MattKaufmann** [comment]
Fixed with commit b0c7e0242d3691cfadfb4e3ea7dc0ee1492e3667.

**Comment by MattKaufmann** [comment]
Sorry, after all this time I still don't get github.  I thought there ought to be a way to mark this issue as "fixed" so that someone else can verify the fix and close it.  But I don't see that, so I'll just close it myself.  (Anyhow, I'm quite confident in the fix, which I've tested.)

**Comment by krobelus** [comment]
Thanks! Now it works for me.

> Sorry, after all this time I still don't get github. I thought there ought to be a way to mark this issue as "fixed" so that someone else can verify the fix and close it. But I don't see that, so I'll just close it myself. (Anyhow, I'm quite confident in the fix, which I've tested.)

I guess I could have tested it earlier.
But if you are reasonably certain that a commit fixes an issue, I think people just close it ([via the commit message](https://help.github.com/articles/closing-issues-using-keywords/)). We can always reopen an issue if it persists.

**Comment by MattKaufmann** [comment]
@krobelus Thanks for the git tip!
