### ISSUE TITLE
cl-str Quicklisp package no longer usable with ACL2s

### ISSUE THREAD

**Issue by mister-walter** [acl2/acl2#999]
I hadn't updated my local copy of ACL2 in a few weeks, but when I did recently I found that a project involving calling ACL2s from raw Lisp no longer works.

The issue is that calling `(ql:quickload :str)` fails with a name-conflict error when run from an ACL2 REPL with ACL2s mode loaded:

```
This is SBCL 1.5.2, an implementation of ANSI Common Lisp.
More information about SBCL is available at <http://www.sbcl.org/>.

SBCL is free software, provided as is, with absolutely no warranty.
It is mostly in the public domain; some portions are provided under
BSD-style licenses.  See the CREDITS and COPYING files in the
distribution for more information.

 ACL2 Version 8.1 built May 21, 2019  17:05:14
                   then May 21, 2019  17:16:22.
 Copyright (C) 2018, Regents of the University of Texas
 ACL2 comes with ABSOLUTELY NO WARRANTY.  This is free software and you
 are welcome to redistribute it under certain conditions.  For details,
 see the LICENSE file distributed with ACL2.

 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 + WARNING: This is NOT an ACL2 release; it is a development snapshot  +
 + (git commit hash: ccffa4dfb04893c8cab1b86547817b6b03e4d49d).        +
 + On rare occasions development snapshots may be incomplete, fragile, +
 + or unable to pass the usual regression tests.                       +
 +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

 Initialized with (INITIALIZE-ACL2 'INCLUDE-BOOK *ACL2-PASS-2-FILES*).
 See the documentation topic note-8-1 for recent changes.
 Note: We have modified the prompt in some underlying Lisps to further
 distinguish it from the ACL2 prompt.

MODIFICATION NOTICE:

ACL2s Mode

ACL2 Version 8.1.  Level 1.  Cbd "/home/drew/tmp/acl2s/".
System books directory "/home/drew/tmp/acl2/books/".
Type :help for help.
Type (good-bye) to quit completely out of ACL2.

ACL2S !>:q

Exiting the ACL2 read-eval-print loop.  To re-enter, execute (LP).
* (ql:quickload :str)
To load "str":
  Load 1 ASDF system:
    str
; Loading "str"
[package cl-ppcre]................................
..................................................
[package str]
debugger invoked on a NAME-CONFLICT in thread
#<THREAD "main thread" RUNNING {10005585B3}>:
  USE-PACKAGE #<PACKAGE "COMMON-LISP"> causes name-conflicts in
  #<PACKAGE "STR"> between the following symbols:
    COMMON-LISP:SET, STR::SET
See also:
  The ANSI Standard, Section 11.1.1.2.5

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [KEEP-OLD                     ] Keep symbols already accessible in STR (shadowing others).
  1: [TAKE-NEW                     ] Make newly exposed symbols accessible in STR, uninterning old ones.
  2: [RESOLVE-CONFLICT             ] Resolve conflict.
  3: [RETRY                        ] Retry
                                     compiling #<CL-SOURCE-FILE "str" "str">.
  4: [ACCEPT                       ] Continue, treating
                                     compiling #<CL-SOURCE-FILE "str" "str"> as
                                     having been successful.
  5:                                 Retry ASDF operation.
  6: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  7:                                 Retry ASDF operation.
  8:                                 Retry ASDF operation after resetting the
                                     configuration.
  9: [ABORT                        ] Give up on "str"
 10:                                 Exit debugger, returning to top level.

(NAME-CONFLICT #<PACKAGE "STR"> USE-PACKAGE #<PACKAGE "COMMON-LISP"> SET STR::SET)
0] 
```

Note that I ran the above command from an ACL2 image with ACL2s mode already loaded; the same thing happens when manually loading in ACL2s mode using the following commands (replacing `<acl2 dir>` with the path to your local ACL2 repo):
```
(add-include-book-dir :acl2s-modes "<acl2 dir>/books/acl2s")
(ld "acl2s-mode.lsp" :dir :acl2s-modes)
(acl2s-defaults :set verbosity-level 1)
(set-inhibit-warnings! "Invariant-risk" "theory")
(reset-prehistory t)
(in-package "ACL2S")
```

I ran a `git bisect` and found that commit ccffa4dfb04893c8cab1b86547817b6b03e4d49d introduced the error.

I have no idea why this issue only occurs after loading ACL2s mode, that's the main thing baffling me. I would expect this issue to occur in standard ACL2 too because of the existing built-in `STR` package (whose exports include those in `*standard-acl2-imports*`, which after the offending commit no longer includes some functions from the `COMMON-LISP` package)

I will note that changing the name of the package created by the cl-str library to something other than "str" also solves the problem.

**Comment by ragerdl** [comment]
Thanks for the clear issue report.

Unfortunately, none of us are really equipped to help with this issue, as we're not really quicklisp folks.  May I inquire as to your application's motivation for calling `(ql:quickload :str)`?

For those following, here's the documentation that explains that calling `(ql:quickload :str)` should work.  http://quickdocs.org/cl-str/


As you point out, the acl2 books can define an `STR` package, which look to be conflicting with that quicklisp library's `str` package. As such, I'm surprised that `cl-str` ever worked.


You could try updating the version of quicklisp distributed with ACL2, but I'm not sure it'll help.  There are some notes on how to update the quicklisp libraries, if you'd like to give it a go:  https://github.com/acl2/acl2/wiki/How-to-update-quicklisp .  I don't have the bandwidth right now to do it myself.

**Comment by ragerdl** [comment]
BTW, while we'd like to be supportive of your use of ACL2[s], I don't think we're inclined to rename our `STR` package.  If it's feasible for you and it works, you might change the quicklisp `cl-str` library to use the `cl-str` or `qstr` package (whatever you prefer).

**Comment by mister-walter** [comment]
Thanks for responding so quickly!

I'm currently using only two small functions from the `cl-str` library, `trim` and `concat`. It would be trivial for me to copy the definitions into my own files and dispense with using this library at all, which is probably what I will do!

I'm using the Roswell tool to manage Lisp implementations on my machine; it installs and keeps updated a version of Quicklisp so it's not clear to me which of ACL2's version and Roswell's version of Quicklisp is being used.

I mainly wanted to report this because of the strange way it seems to interact with ACL2s, and because it is a regression from previous ACL2 versions. It should be simple to fix this on my end, definitely doesn't rise to the level of importance necessitating changing the name of ACL2's `STR` package!

**Comment by ragerdl** [comment]
Haha, glad to hear you have a work-around :)

In an ideal world we'd fix whatever the underlying issue is, but it's really something any of us are going to actually want to do.  That, combined with you having a work-around, I think we'll opt not to fix this one.

BTW, do you know about http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index.html?topic=STR____CONCATENATION and http://www.cs.utexas.edu/users/moore/acl2/manuals/current/manual/index.html?topic=STR____TRIM

**Comment by mister-walter** [comment]
Thanks for the links to those functions! When/if I find some time I'll take a look at the ACL2s books and try to figure out exactly why this only happens after ACL2s mode is loaded. I'll close for now; feel free to reopen if you think that makes sense.
